repos:
      - repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.13.2 # Use the latest stable Ruff version
        hooks:
          - id: ruff-check # Runs the linter
#            args: [--fix] # Automatically fixes fixable issues
          - id: ruff-format # Applies formatting

