[environment]
python = "./.venv"
root = ["."]

[src]
exclude = [
    "**/experiments",
    "**/scraps",
    "**/benchmarks",
    "**/pyarmor_runtime_000000",
]

[[overrides]]
include = ["src/barks-reader/tests/unit/test_main_screen_nav.py"]

[overrides.rules]
unused-ignore-comment = "ignore"
