from __future__ import annotations

from .barks_tags import TagCategories, TagGroups, Tags
from .barks_titles import NON_COMIC_TITLES, Titles

BARKS_TAG_CATEGORIES = {
    TagCategories.CHARACTERS: [
        TagGroups.PRIMARY_CHARACTERS,
        TagGroups.SECONDARY_CHARACTERS,
        TagGroups.ONE_OFF_CHARACTERS,
    ],
    TagCategories.FAVOURITES: [
        Tags.BARKS_FAVOURITES,
        Tags.EVERY_GEEK_FAVOURITES,
        Tags.PERSONAL_FAVOURITES,
        Tags.PETER_SCHILLING_FAVOURITES,
        Tags.WIKI_NOTABLE_STORIES,
        Tags.CLASSICS,
    ],
    TagCategories.PLACES: [
        Tags.AEOLIAN_ISLANDS,
        TagGroups.AFRICA,
        Tags.ALASKA,
        Tags.ALGERIA,
        Tags.ANDES,
        Tags.ANTARCTICA,
        Tags.ARABIAN_PENINSULA,
        Tags.ARCTIC_OCEAN,
        Tags.ATLANTIS,
        TagGroups.ASIA,
        # Tags.AUSTRALIA,
        TagGroups.AUSTRALASIA,
        Tags.BAGDAD,
        Tags.BARNACLE_BAY,
        Tags.BRITISH_GUIANA,
        Tags.CANADA,
        Tags.CENTRAL_AFRICA,
        Tags.CHINA,
        Tags.CONGO,
        TagGroups.COUNTRIES,
        Tags.CRETE,
        Tags.DAMASCUS,
        Tags.DUCKBURG,
        Tags.EGYPT,
        TagGroups.EUROPE,
        Tags.FLORIDA,
        Tags.FRANCE,
        Tags.GERMANY,
        Tags.GREECE,
        Tags.HIMALAYAS,
        Tags.HONDORICA,
        Tags.INDIA,
        Tags.INDIAN_OCEAN,
        Tags.INDO_CHINA,
        Tags.IRAQ,
        Tags.ITALY,
        Tags.ITSA_FAKA,
        Tags.KAKIMAW_COUNTRY,
        Tags.LIBYA,
        Tags.LABRADOR,
        Tags.MALI,
        Tags.MISSISSIPPI,
        Tags.MONGOLIA,
        Tags.MOROCCO,
        Tags.NEWFOUNDLAND,
        Tags.NIAGARA_FALLS,
        TagGroups.NORTH_AMERICA,
        Tags.NORWAY,
        Tags.OHIO,
        Tags.OLD_DEMON_TOOTH,
        Tags.PAKISTAN,
        Tags.PERSIA,
        Tags.PERU,
        Tags.PLAIN_AWFUL,
        Tags.RUSSIA,
        Tags.SCOTLAND,
        Tags.SOUTH_AFRICA,
        TagGroups.SOUTH_AMERICA,
        Tags.SPAIN,
        Tags.SUDAN,
        Tags.SWEDEN,
        Tags.SWITZERLAND,
        Tags.SYDNEY,
        Tags.SYRIA,
        Tags.TANGANYIKA,
        Tags.TANGKOR_WAT,
    ],
    TagCategories.THEMES: [
        Tags.CENSORED_STORIES_BUT_FIXED,
        TagGroups.CHEMISTRY,
        Tags.CHRISTMAS_STORIES,
        TagGroups.CULTURAL_GROUPS,
        TagGroups.DRUGS,
        Tags.HYPNOSIS,
        Tags.MAGIC,
        Tags.PHOTOGRAPHY,
        Tags.NEW_VERSIONS,
    ],
    TagCategories.THINGS: [
        Tags.AIRPLANES,
        Tags.CAMERAS,
        TagGroups.CARS,
        TagGroups.CHEMICAL_NAMES,
        Tags.CIGARETTES,
        Tags.FIRE,
        Tags.SQUARE_EGGS,
        Tags.WORRY_ROOM,
    ],
}

BARKS_TAG_GROUPS = {
    TagGroups.AFRICA: [
        Tags.ALGERIA,
        Tags.ARABIAN_PENINSULA,
        Tags.CENTRAL_AFRICA,
        Tags.CONGO,
        Tags.EGYPT,
        Tags.LIBYA,
        Tags.MALI,
        Tags.MOROCCO,
        Tags.SOUTH_AFRICA,
        Tags.SUDAN,
        Tags.TANGANYIKA,
    ],
    TagGroups.ASIA: [
        Tags.BAGDAD,
        Tags.CHINA,
        Tags.DAMASCUS,
        Tags.INDO_CHINA,
        Tags.HIMALAYAS,
        Tags.INDIA,
        Tags.IRAQ,
        Tags.ITSA_FAKA,
        Tags.MONGOLIA,
        Tags.PAKISTAN,
        Tags.PERSIA,
        Tags.SYRIA,
        Tags.TANGKOR_WAT,
    ],
    TagGroups.AUSTRALASIA: [
        Tags.AUSTRALIA,
        Tags.SYDNEY,
    ],
    TagGroups.CARS: [
        Tags.CAR_313,
        Tags.HDL_DRIVING_CAR,
    ],
    TagGroups.CHEMICAL_NAMES: [
        Tags.ALKALI,
        Tags.CALCIUM,
        Tags.CARBON,
        Tags.COPPER,
        Tags.COLUMBIUM,
        Tags.DUCKMITE,
        Tags.FORBIDIUM,
        Tags.ISOTOPES,
        Tags.LITHIUM,
        Tags.MANGANESE,
        Tags.MERCURY,
        Tags.NAPHTHA,
        Tags.NEUTRON,
        Tags.NICKEL,
        Tags.NITROGEN,
        Tags.NITROGLYCERIN,
        Tags.NOSUCHIUM,
        Tags.OPA,
        Tags.OXYGEN,
        Tags.PHOSPHORUS,
        Tags.PLASMA,
        Tags.PLATINUM,
        Tags.POTASH,
        Tags.SELENIUM,
        Tags.STROMBOLIUM,
        Tags.SULPHUR,
        Tags.SULPHURIC_ACID,
        Tags.TANTALUM,
        Tags.THORIUM,
        Tags.WEEMITE,
        Tags.WOLFRAMITE,
        Tags.WHATTISIUM,
        Tags.YOUGUESSIUM,
        Tags.ZINC,
        Tags.ZIRCONIUM,
    ],
    TagGroups.CHEMISTRY: [
        Tags.CHEMICAL_FORMULA,
        TagGroups.CHEMICAL_NAMES,
        Tags.DUCKMITE,
        Tags.WEEMITE,
    ],
    TagGroups.COUNTRIES: [
        Tags.ALGERIA,
        Tags.BRITISH_GUIANA,
        Tags.CANADA,
        Tags.CHINA,
        Tags.CONGO,
        Tags.CRETE,
        Tags.EGYPT,
        Tags.FRANCE,
        Tags.GERMANY,
        Tags.GREECE,
        Tags.HONDORICA,
        Tags.INDIA,
        Tags.INDO_CHINA,
        Tags.IRAQ,
        Tags.ITALY,
        Tags.LIBYA,
        Tags.MALI,
        Tags.MONGOLIA,
        Tags.MOROCCO,
        Tags.NORWAY,
        Tags.PAKISTAN,
        Tags.PERSIA,
        Tags.PERU,
        Tags.RUSSIA,
        Tags.SCOTLAND,
        Tags.SOUTH_AFRICA,
        Tags.SPAIN,
        Tags.SUDAN,
        Tags.SWEDEN,
        Tags.SWITZERLAND,
        Tags.SYRIA,
        Tags.TANGANYIKA,
    ],
    TagGroups.CULTURAL_GROUPS: [
        Tags.AUSTRALIAN_ABORIGINALS,
        Tags.AWFULTONIANS,
        Tags.GNEEZLES,
        Tags.INUIT,
        Tags.JIVARO,
        Tags.KAKIMAW_INDIANS,
        Tags.PEEWEEGAH_INDIANS,
        Tags.STICKAREE_INDIANS,
    ],
    TagGroups.DRUGS: [
        Tags.CIGARETTES,
    ],
    TagGroups.EUROPE: [
        Tags.AEOLIAN_ISLANDS,
        Tags.CRETE,
        Tags.FRANCE,
        Tags.GERMANY,
        Tags.GREECE,
        Tags.ITALY,
        Tags.NORWAY,
        Tags.RUSSIA,
        Tags.SCOTLAND,
        Tags.SPAIN,
        Tags.SWEDEN,
        Tags.SWITZERLAND,
    ],
    TagGroups.NORTH_AMERICA: [
        Tags.ALASKA,
        Tags.CANADA,
        Tags.FLORIDA,
        Tags.LABRADOR,
        Tags.MISSISSIPPI,
        Tags.NEWFOUNDLAND,
        Tags.NIAGARA_FALLS,
        Tags.OHIO,
    ],
    TagGroups.ONE_OFF_CHARACTERS: [
        Tags.APPLECHEEKS_TEENGIGGLE,
        Tags.ARGUS_MCFIENDY,
        Tags.AZURE_BLUE,
        Tags.BENZENE_BANZOONY,
        Tags.BOMBIE_THE_ZOMBIE,
        Tags.BOP_BOP,
        Tags.CABBAGE_PROFESSOR,
        Tags.CARVER_BEAKOFF,
        Tags.CHISEL_MC_SUE,
        Tags.CORNELIUS_MC_COBB,
        Tags.EL_DORADO,
        Tags.FERMIES,
        Tags.FOOLA_ZOOLA,
        Tags.GNEEZLES,
        Tags.J_MORGANBILT_GILTWHISKERS,
        Tags.JAYNE_GIRLSFIELD,
        Tags.JUGHEAD_JONES,
        Tags.LONGHORN_TALLGRASS,
        Tags.MAD_SCIENTIST,
        Tags.MOURNFUL_MARY,
        Tags.PULPHEART_CLABBERHEAD,
        Tags.TERRIES,
    ],
    TagGroups.OTHER_PLACES: [
        Tags.ANTARCTICA,
        Tags.ARCTIC_OCEAN,
        Tags.ATLANTIS,
        Tags.BARNACLE_BAY,
        Tags.DUCKBURG,
        Tags.HONDORICA,
        Tags.INDIAN_OCEAN,
        Tags.KAKIMAW_COUNTRY,
        Tags.OLD_DEMON_TOOTH,
    ],
    TagGroups.PIG_VILLAINS: [
        Tags.HASSAN_BEN_JAILD,
        Tags.MR_MC_SWINE,
        Tags.P_J_MC_BRINE,
        Tags.PORKMAN_DE_LARDO,
        Tags.SOAPY_SLICK,
    ],
    TagGroups.PRIMARY_CHARACTERS: [
        Tags.BEAGLE_BOYS,
        Tags.DAISY,
        Tags.GLADSTONE_GANDER,
        Tags.GYRO_GEARLOOSE,
        Tags.GYRO_NOT_IN_GG,
        Tags.JUNIOR_WOODCHUCKS,
        Tags.SCROOGE_NOT_IN_US,
    ],
    TagGroups.SECONDARY_CHARACTERS: [
        Tags.FLINTHEART_GLOMGOLD,
        Tags.GENERAL_SNOZZIE,
        Tags.HERBERT,
        Tags.MAGICA_DE_SPELL,
        Tags.NEIGHBOR_JONES,
        TagGroups.PIG_VILLAINS,
    ],
    TagGroups.SOUTH_AMERICA: [
        Tags.ANDES,
        Tags.BRITISH_GUIANA,
        Tags.PERU,
        Tags.PLAIN_AWFUL,
    ],
}

BARKS_TAGGED_TITLES: dict[Tags, list[Titles]] = {
    Tags.AEOLIAN_ISLANDS: [Titles.CAVE_OF_THE_WINDS],
    Tags.AIRPLANES: [
        Titles.TRUANT_NEPHEWS_THE,
        Titles.MASTER_RAINMAKER_THE,
        Titles.CROWN_OF_THE_MAYAS,
        Titles.ADVENTURE_DOWN_UNDER,
        Titles.NORTH_OF_THE_YUKON,
        Titles.TRAIL_OF_THE_UNICORN,
        Titles.TWO_WAY_LUCK,
        Titles.GREAT_WIG_MYSTERY_THE,
        Titles.BALLOONATICS,
        Titles.FROZEN_GOLD,
        Titles.LOST_FRONTIER,
        Titles.FRAIDY_FALCON_THE,
        Titles.TRALLA_LA,
        Titles.SO_FAR_AND_NO_SAFARI,
        Titles.VOLCANO_VALLEY,
        Titles.VOODOO_HOODOO,
        Titles.SPICY_TALE_A,
        Titles.LAND_OF_THE_PYGMY_INDIANS,
        Titles.GOOD_DEEDS_THE,
        Titles.SECRET_OF_ATLANTIS_THE,
        Titles.SMOKE_WRITER_IN_THE_SKY,
        Titles.QUEEN_OF_THE_WILD_DOG_PACK_THE,
    ],
    Tags.ALASKA: [
        Titles.FROZEN_GOLD,
        Titles.LUCK_OF_THE_NORTH,
        Titles.BACK_TO_THE_KLONDIKE,
        Titles.GOLDEN_NUGGET_BOAT_THE,
    ],
    Tags.ALGERIA: [Titles.ROCKET_RACE_AROUND_THE_WORLD],
    Tags.ALKALI: [Titles.TWENTY_FOUR_CARAT_MOON_THE],
    Tags.ANDES: [Titles.LOST_IN_THE_ANDES],
    Tags.ANTARCTICA: [Titles.COLD_BARGAIN_A],
    Tags.APPLECHEEKS_TEENGIGGLE: [Titles.PERSISTENT_POSTMAN_THE],
    Tags.ARABIAN_PENINSULA: [
        Titles.MINES_OF_KING_SOLOMON_THE,
        Titles.MONEY_CHAMP_THE,
        Titles.PIPELINE_TO_DANGER,
        Titles.CAVE_OF_ALI_BABA,
        Titles.MCDUCK_OF_ARABIA,
    ],
    Tags.ARCTIC_OCEAN: [Titles.LUCK_OF_THE_NORTH],
    Tags.ARGUS_MCFIENDY: [Titles.DARKEST_AFRICA],
    Tags.ARTICLES: NON_COMIC_TITLES,
    Tags.ATLANTIS: [Titles.SECRET_OF_ATLANTIS_THE],
    Tags.AUSTRALIA: [
        Titles.ADVENTURE_DOWN_UNDER,
        Titles.RICHES_RICHES_EVERYWHERE,
        Titles.QUEEN_OF_THE_WILD_DOG_PACK_THE,
    ],
    Tags.AUSTRALIAN_ABORIGINALS: [Titles.ADVENTURE_DOWN_UNDER],
    Tags.AWFULTONIANS: [Titles.LOST_IN_THE_ANDES],
    Tags.AZURE_BLUE: [Titles.GOLDEN_HELMET_THE],
    Tags.BAGDAD: [Titles.FABULOUS_PHILOSOPHERS_STONE_THE],
    Tags.BARKS_FAVOURITES: [
        # This list of Barks' favorites is from https://www.cbarks.dk/thefavourites.htm
        Titles.LOST_IN_THE_ANDES,
        Titles.IN_OLD_CALIFORNIA,
        Titles.RIP_VAN_DONALD,
        Titles.FINANCIAL_FABLE_A,
        Titles.OMELET,
        Titles.HORSERADISH_STORY_THE,
        Titles.SECRET_OF_ATLANTIS_THE,
        Titles.LAND_OF_THE_PYGMY_INDIANS,
        Titles.ISLAND_IN_THE_SKY,
        Titles.MICRO_DUCKS_FROM_OUTER_SPACE,
        Titles.GHOST_OF_THE_GROTTO_THE,
        Titles.LAND_OF_THE_TOTEM_POLES,
        Titles.IN_ANCIENT_PERSIA,
        Titles.GOLDEN_HELMET_THE,
        Titles.VACATION_TIME,
    ],
    Tags.BARNACLE_BAY: [Titles.NO_SUCH_VARMINT],
    Tags.BEAGLE_BOYS: [
        Titles.TERROR_OF_THE_BEAGLE_BOYS,
        Titles.BIG_BIN_ON_KILLMOTOR_HILL_THE,
        Titles.ONLY_A_POOR_OLD_MAN,
        Titles.ROUND_MONEY_BIN_THE,
        Titles.MENEHUNE_MYSTERY_THE,
        Titles.SEVEN_CITIES_OF_CIBOLA_THE,
        Titles.MYSTERIOUS_STONE_RAY_THE,
        Titles.FANTASTIC_RIVER_RACE_THE,
        Titles.MONEY_WELL_THE,
        Titles.CHRISTMAS_IN_DUCKBURG,
        Titles.STRANGE_SHIPWRECKS_THE,
        Titles.TWENTY_FOUR_CARAT_MOON_THE,
        Titles.PAUL_BUNYAN_MACHINE_THE,
        Titles.ALL_AT_SEA,
        Titles.TREE_TRICK,
        Titles.BILLIONS_IN_THE_HOLE,
        Titles.GIFT_LION,
        Titles.DEEP_DOWN_DOINGS,
        Titles.UNSAFE_SAFE_THE,
        Titles.TRICKY_EXPERIMENT,
        Titles.STATUS_SEEKER_THE,
        Titles.CASE_OF_THE_STICKY_MONEY_THE,
        Titles.ISLE_OF_GOLDEN_GEESE,
        Titles.HOW_GREEN_WAS_MY_LETTUCE,
        Titles.GIANT_ROBOT_ROBBERS_THE,
        Titles.HOUSE_OF_HAUNTS,
        Titles.HEEDLESS_HORSEMAN_THE,
        Titles.DOOM_DIAMOND_THE,
        Titles.MR_PRIVATE_EYE,
        Titles.DELIVERY_DILEMMA,
    ],
    Tags.BENZENE_BANZOONY: [Titles.FIREBUG_THE],
    Tags.BOMBIE_THE_ZOMBIE: [Titles.VOODOO_HOODOO],
    Tags.BOP_BOP: [Titles.VOODOO_HOODOO],
    Tags.BRITISH_GUIANA: [Titles.GILDED_MAN_THE],
    Tags.CABBAGE_PROFESSOR: [Titles.MYSTERIOUS_STONE_RAY_THE],
    Tags.CALCIUM: [Titles.KRANKENSTEIN_GYRO],
    Tags.CAMERAS: [
        Titles.CAMERA_CRAZY,
        Titles.PECKING_ORDER,
        Titles.VACATION_TIME,
        Titles.SECRET_RESOLUTIONS,
        Titles.MYSTERY_OF_THE_LOCH,
        Titles.MEDALING_AROUND,
        Titles.DUCKS_EYE_VIEW_OF_EUROPE_A,
    ],
    Tags.CANADA: [Titles.FROZEN_GOLD, Titles.BACK_TO_THE_KLONDIKE],
    Tags.CARBON: [Titles.TWENTY_FOUR_CARAT_MOON_THE],
    Tags.CARVER_BEAKOFF: [Titles.FIREBUG_THE],
    Tags.CAR_313: [
        Titles.DONALDS_MONSTER_KITE,
        Titles.MAD_CHEMIST_THE,
        Titles.RIP_VAN_DONALD,
        Titles.VOLCANO_VALLEY,
        Titles.SHERIFF_OF_BULLET_VALLEY,
        Titles.VACATION_TIME,
    ],
    Tags.CENSORED_STORIES_BUT_FIXED: [
        Titles.BACK_TO_THE_KLONDIKE,
        Titles.BILL_COLLECTORS_THE,
        Titles.BONGO_ON_THE_CONGO,
        Titles.FIREBUG_THE,
        Titles.FROZEN_GOLD,
        Titles.GOLDEN_CHRISTMAS_TREE_THE,
        Titles.GOLDEN_FLEECING_THE,
        Titles.GOOD_DEEDS,
        Titles.ICEBOX_ROBBER_THE,
        Titles.LAND_BENEATH_THE_GROUND,
        Titles.LOST_IN_THE_ANDES,
        Titles.LOVELORN_FIREMAN_THE,
        Titles.SILENT_NIGHT,
        Titles.SWIMMING_SWINDLERS,
        Titles.TERROR_OF_THE_RIVER_THE,
        Titles.TRICK_OR_TREAT,
        Titles.VOODOO_HOODOO,
    ],
    Tags.CENTRAL_AFRICA: [
        Titles.DARKEST_AFRICA,
        Titles.VOODOO_HOODOO,
        Titles.JUNGLE_HI_JINKS,
        Titles.WISHING_WELL_THE,
        Titles.JUNGLE_BUNGLE,
        Titles.SO_FAR_AND_NO_SAFARI,
    ],
    Tags.CHEMICAL_FORMULA: [
        Titles.MAD_CHEMIST_THE,
        Titles.BEAR_TAMER_THE,
        Titles.MIXED_UP_MIXER,
        Titles.PIED_PIPER_OF_DUCKBURG_THE,
    ],
    Tags.CHISEL_MC_SUE: [Titles.HORSERADISH_STORY_THE],
    Tags.CHINA: [Titles.MONEY_CHAMP_THE],
    Tags.CHRISTMAS_STORIES: [
        Titles.DONALD_DUCKS_BEST_CHRISTMAS,
        Titles.SILENT_NIGHT,
        Titles.SANTAS_STORMY_VISIT,
        Titles.CHRISTMAS_ON_BEAR_MOUNTAIN,
        Titles.TOYLAND,
        Titles.GOLDEN_CHRISTMAS_TREE_THE,
        Titles.WINTERTIME_WAGER,
        Titles.NEW_TOYS,
        Titles.LETTER_TO_SANTA,
        Titles.YOU_CANT_WIN,
        Titles.TURKEY_RAFFLE,
        Titles.CHRISTMAS_FOR_SHACKTOWN_A,
        Titles.TURKEY_WITH_ALL_THE_SCHEMINGS,
        Titles.HAMMY_CAMEL_THE,
        Titles.SEARCH_FOR_THE_CUSPIDORIA,
        Titles.THREE_UN_DUCKS,
        Titles.BLACK_PEARLS_OF_TABU_YAMA_THE,
        Titles.CODE_OF_DUCKBURG_THE,
        Titles.CHRISTMAS_IN_DUCKBURG,
        Titles.ROCKET_ROASTED_CHRISTMAS_TURKEY,
        Titles.NORTHEASTER_ON_CAPE_QUACK,
        Titles.CHRISTMAS_CHEERS,
        Titles.DOUBLE_MASQUERADE,
        Titles.THRIFTY_SPENDTHRIFT_THE,
    ],
    Tags.CIGARETTES: [
        Titles.LIMBER_W_GUEST_RANCH_THE,
        Titles.DONALD_DUCK_AND_THE_MUMMYS_RING,
        Titles.MAD_CHEMIST_THE,
        Titles.SWIMMING_SWINDLERS,
        Titles.GOING_BUGGY,
        Titles.JAM_ROBBERS,
        Titles.SHERIFF_OF_BULLET_VALLEY,
        Titles.DANGEROUS_DISGUISE,
        Titles.VACATION_TIME,
        Titles.BILLIONS_TO_SNEEZE_AT,
    ],
    Tags.CLASSICS: [
        # As chosen by GLK
        Titles.LOST_IN_THE_ANDES,
        Titles.GHOST_OF_THE_GROTTO_THE,
        Titles.OLD_CASTLES_SECRET_THE,
        Titles.SHERIFF_OF_BULLET_VALLEY,
        Titles.LAND_OF_THE_TOTEM_POLES,
        Titles.IN_ANCIENT_PERSIA,
        Titles.VACATION_TIME,
        Titles.IN_OLD_CALIFORNIA,
        Titles.GILDED_MAN_THE,
        Titles.GOLDEN_HELMET_THE,
        Titles.ONLY_A_POOR_OLD_MAN,
        Titles.BACK_TO_THE_KLONDIKE,
        Titles.MASTER_RAINMAKER_THE,
        Titles.FINANCIAL_FABLE_A,
        Titles.HYPNO_GUN_THE,
        Titles.BEE_BUMBLES,
    ],
    Tags.COLUMBIUM: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.CONGO: [Titles.BONGO_ON_THE_CONGO],
    Tags.COPPER: [
        Titles.GOLD_FINDER_THE,
        Titles.ONLY_A_POOR_OLD_MAN,
        Titles.FABULOUS_PHILOSOPHERS_STONE_THE,
        Titles.RICHES_RICHES_EVERYWHERE,
        Titles.LAND_OF_THE_PYGMY_INDIANS,
    ],
    Tags.CORNELIUS_MC_COBB: [Titles.VOODOO_HOODOO],
    Tags.CRETE: [Titles.FABULOUS_PHILOSOPHERS_STONE_THE],
    Tags.DAISY: [
        Titles.MIGHTY_TRAPPER_THE,
        Titles.EYES_IN_THE_DARK,
        Titles.DONALD_TAMES_HIS_TEMPER,
        Titles.BICEPS_BLUES,
        Titles.GOLD_FINDER_THE,
        Titles.CANTANKEROUS_CAT_THE,
        Titles.PICNIC_TRICKS,
        Titles.MAGICAL_MISERY,
        Titles.WALTZ_KING_THE,
        Titles.WINTERTIME_WAGER,
        Titles.WATCHING_THE_WATCHMAN,
        Titles.GOING_APE,
        Titles.ROCKET_RACE_TO_THE_MOON,
        Titles.GLADSTONE_RETURNS,
        Titles.PEARLS_OF_WISDOM,
        Titles.DONALD_DUCKS_WORST_NIGHTMARE,
        Titles.DONALDS_LOVE_LETTERS,
        Titles.LAND_OF_THE_TOTEM_POLES,
        Titles.WILD_ABOUT_FLOWERS,
        Titles.BIG_TOP_BEDLAM,
        Titles.YOU_CANT_GUESS,
        Titles.KNIGHTLY_RIVALS,
        Titles.CHRISTMAS_FOR_SHACKTOWN_A,
        Titles.ATTIC_ANTICS,
        Titles.GLADSTONES_USUAL_VERY_GOOD_YEAR,
        Titles.ROCKET_WING_SAVES_THE_DAY,
        Titles.HOBBLIN_GOBLINS,
        Titles.OMELET,
        Titles.CHARITABLE_CHORE_A,
        Titles.FLIP_DECISION,
        Titles.MY_LUCKY_VALENTINE,
        Titles.EASTER_ELECTION_THE,
        Titles.MASTER_RAINMAKER_THE,
        Titles.RAFFLE_REVERSAL,
        Titles.FIX_UP_MIX_UP,
        Titles.DAFFY_TAFFY_PULL_THE,
        Titles.KNIGHT_IN_SHINING_ARMOR,
        Titles.LOSING_FACE,
        Titles.DAY_DUCKBURG_GOT_DYED_THE,
        Titles.RED_APPLE_SAP,
        Titles.DODGING_MISS_DAISY,
        Titles.WATER_SKI_RACE,
        Titles.TRACKING_SANDY,
        Titles.BEACHCOMBERS_PICNIC_THE,
        Titles.DRAMATIC_DONALD,
        Titles.ROCKET_ROASTED_CHRISTMAS_TURKEY,
        Titles.LOVELORN_FIREMAN_THE,
        Titles.KNIGHTS_OF_THE_FLYING_SLEDS,
        Titles.WEATHER_WATCHERS_THE,
        Titles.VILLAGE_BLACKSMITH_THE,
        Titles.TURKEY_TROUBLE,
        Titles.BOXED_IN,
        Titles.MR_PRIVATE_EYE,
        Titles.JINXED_JALOPY_RACE_THE,
        Titles.HAVE_GUN_WILL_DANCE,
        Titles.OLYMPIAN_TORCH_BEARER_THE,
        Titles.HERO_OF_THE_DIKE,
        Titles.BEAUTY_BUSINESS_THE,
        Titles.NOT_SO_ANCIENT_MARINER_THE,
    ],
    Tags.DAMASCUS: [Titles.FABULOUS_PHILOSOPHERS_STONE_THE],
    Tags.DUCKBURG: [
        Titles.HIGH_WIRE_DAREDEVILS,
        Titles.CHRISTMAS_IN_DUCKBURG,
        Titles.TITANIC_ANTS_THE,
        Titles.LAND_BENEATH_THE_GROUND,
        Titles.HIS_HANDY_ANDY,
        Titles.DUCKBURGS_DAY_OF_PERIL,
        Titles.GIANT_ROBOT_ROBBERS_THE,
        Titles.GREAT_DUCKBURG_FROG_JUMPING_CONTEST_THE,
        Titles.OLYMPIC_HOPEFUL_THE,
        Titles.DAY_DUCKBURG_GOT_DYED_THE,
        Titles.CODE_OF_DUCKBURG_THE,
        Titles.BLACK_WEDNESDAY,
        Titles.DUCKBURG_PET_PARADE_THE,
    ],
    Tags.DUCKMITE: [Titles.MAD_CHEMIST_THE],
    Tags.EGYPT: [Titles.DONALD_DUCK_AND_THE_MUMMYS_RING],
    Tags.EL_DORADO: [Titles.GILDED_MAN_THE],
    Tags.EVERY_GEEK_FAVOURITES: [
        # This list from https://everygeek.net/carl-barks-comics-ducktales-fan
        Titles.BACK_TO_THE_KLONDIKE,
        Titles.FABULOUS_PHILOSOPHERS_STONE_THE,
        Titles.GOLDEN_FLEECING_THE,
        Titles.VACATION_TIME,
        Titles.GOLDEN_HELMET_THE,
        Titles.LUCK_OF_THE_NORTH,
        Titles.STATUESQUE_SPENDTHRIFTS,
    ],
    Tags.FERMIES: [Titles.LAND_BENEATH_THE_GROUND],
    Tags.FIRE: [Titles.FIREBUG_THE, Titles.FIREMAN_DONALD, Titles.LOVELORN_FIREMAN_THE],
    Tags.FLINTHEART_GLOMGOLD: [
        Titles.SECOND_RICHEST_DUCK_THE,
        Titles.MONEY_CHAMP_THE,
        Titles.SO_FAR_AND_NO_SAFARI,
    ],
    Tags.FLORIDA: [Titles.CHARITABLE_CHORE_A],
    Tags.FOOLA_ZOOLA: [Titles.VOODOO_HOODOO],
    Tags.FORBIDIUM: [Titles.FORBIDIUM_MONEY_BIN_THE],
    Tags.FRANCE: [Titles.DANGEROUS_DISGUISE],
    Tags.GENERAL_SNOZZIE: [
        Titles.PHANTOM_OF_NOTRE_DUCK_THE,
        Titles.DODGING_MISS_DAISY,
        Titles.BLACK_FOREST_RESCUE_THE,
        Titles.HOUND_HOUNDER,
        Titles.MEDALING_AROUND,
        Titles.BEACH_BOY,
        Titles.DUCK_OUT_OF_LUCK,
    ],
    Tags.GERMANY: [Titles.FABULOUS_PHILOSOPHERS_STONE_THE],
    Tags.GLADSTONE_GANDER: [
        Titles.YOU_CANT_GUESS,
        Titles.SECRET_OF_HONDORICA,
        Titles.RACE_TO_THE_SOUTH_SEAS,
        Titles.LUCK_OF_THE_NORTH,
        Titles.TRAIL_OF_THE_UNICORN,
        Titles.CHRISTMAS_FOR_SHACKTOWN_A,
        Titles.GILDED_MAN_THE,
        Titles.LOST_RABBIT_FOOT_THE,
        Titles.BEAR_TAMER_THE,
        Titles.GOING_TO_PIECES,
        Titles.KITTY_GO_ROUND,
        Titles.GOLDEN_NUGGET_BOAT_THE,
        Titles.SEEING_IS_BELIEVING,
        Titles.BILLION_DOLLAR_SAFARI_THE,
        Titles.WINTERTIME_WAGER,
        Titles.GLADSTONE_RETURNS,
        Titles.LINKS_HIJINKS,
        Titles.RIVAL_BEACHCOMBERS,
        Titles.GOLDILOCKS_GAMBIT_THE,
        Titles.DONALDS_LOVE_LETTERS,
        Titles.WILD_ABOUT_FLOWERS,
        Titles.FINANCIAL_FABLE_A,
        Titles.KNIGHTLY_RIVALS,
        Titles.GLADSTONES_LUCK,
        Titles.GLADSTONES_USUAL_VERY_GOOD_YEAR,
        Titles.GLADSTONES_TERRIBLE_SECRET,
        Titles.GEMSTONE_HUNTERS,
        Titles.CHARITABLE_CHORE_A,
        Titles.MY_LUCKY_VALENTINE,
        Titles.EASTER_ELECTION_THE,
        Titles.SOME_HEIR_OVER_THE_RAINBOW,
        Titles.MASTER_RAINMAKER_THE,
        Titles.RAFFLE_REVERSAL,
        Titles.SALMON_DERBY,
        Titles.DAFFY_TAFFY_PULL_THE,
        Titles.GOOD_CANOES_AND_BAD_CANOES,
        Titles.SEARCHING_FOR_A_SUCCESSOR,
        Titles.RED_APPLE_SAP,
        Titles.TENDERFOOT_TRAP_THE,
        Titles.CODE_OF_DUCKBURG_THE,
        Titles.ROCKET_RACE_AROUND_THE_WORLD,
        Titles.MOCKING_BIRD_RIDGE,
        Titles.DRAMATIC_DONALD,
        Titles.BEACHCOMBERS_PICNIC_THE,
        Titles.LOVELORN_FIREMAN_THE,
        Titles.TURKEY_TROUBLE,
        Titles.DUCK_LUCK,
        Titles.JINXED_JALOPY_RACE_THE,
        Titles.DUCKBURG_PET_PARADE_THE,
        Titles.HERO_OF_THE_DIKE,
        Titles.DUCK_OUT_OF_LUCK,
        Titles.NOT_SO_ANCIENT_MARINER_THE,
    ],
    Tags.GNEEZLES: [Titles.MYSTERY_OF_THE_SWAMP],
    Tags.GREECE: [
        Titles.FABULOUS_PHILOSOPHERS_STONE_THE,
        Titles.GOLDEN_FLEECING_THE,
        Titles.ODDBALL_ODYSSEY,
        Titles.INSTANT_HERCULES,
    ],
    Tags.GYRO_GEARLOOSE: [
        Titles.GRANDMAS_PRESENT,
        Titles.HOBBLIN_GOBLINS,
        Titles.FORBIDIUM_MONEY_BIN_THE,
        Titles.AUGUST_ACCIDENT,
        Titles.WEATHER_WATCHERS_THE,
        Titles.GAB_MUFFER_THE,
        Titles.STUBBORN_STORK_THE,
        Titles.MILKTIME_MELODIES,
        Titles.LOST_RABBIT_FOOT_THE,
        Titles.BIRD_CAMERA_THE,
        Titles.ODD_ORDER_THE,
        Titles.CALL_OF_THE_WILD_THE,
        Titles.CAVE_OF_THE_WINDS,
        Titles.MIXED_UP_MIXER,
        Titles.MADBALL_PITCHER_THE,
        Titles.BEAR_TAMER_THE,
        Titles.TALE_OF_THE_TAPE,
        Titles.HIS_SHINING_HOUR,
        Titles.PICNIC,
        Titles.SEVEN_CITIES_OF_CIBOLA_THE,
        Titles.HEIRLOOM_WATCH,
        Titles.TRAPPED_LIGHTNING,
        Titles.INVENTOR_OF_ANYTHING,
        Titles.CAT_BOX_THE,
        Titles.FORECASTING_FOLLIES,
        Titles.FISHING_MYSTERY,
        Titles.SURE_FIRE_GOLD_FINDER_THE,
        Titles.GYRO_BUILDS_A_BETTER_HOUSE,
        Titles.ROSCOE_THE_ROBOT,
        Titles.GETTING_THOR,
        Titles.KNOW_IT_ALL_MACHINE_THE,
        Titles.GYRO_GOES_FOR_A_DIP,
        Titles.HOUSE_ON_CYCLONE_HILL_THE,
        Titles.WISHING_WELL_THE,
        Titles.KRANKENSTEIN_GYRO,
        Titles.FIREFLY_TRACKER_THE,
        Titles.INVENTORS_CONTEST_THE,
        Titles.OODLES_OF_OOMPH,
        Titles.WAR_PAINT,
        Titles.FISHY_WARDEN,
        Titles.THAT_SMALL_FEELING,
        Titles.YOU_CANT_WIN,
        Titles.WILY_RIVAL,
        Titles.FAST_AWAY_CASTAWAY,
        Titles.DUCKBURGS_DAY_OF_PERIL,
        Titles.GREAT_POP_UP_THE,
        Titles.MADCAP_INVENTORS,
        Titles.FINNY_FUN,
        Titles.POSTHASTY_POSTMAN,
        Titles.SNOW_DUSTER,
        Titles.HELPERS_HELPING_HAND_A,
        Titles.MAN_VERSUS_MACHINE,
        Titles.JONAH_GYRO,
        Titles.GLADSTONES_TERRIBLE_SECRET,
        Titles.THINK_BOX_BOLLIX_THE,
        Titles.TALKING_DOG_THE,
        Titles.WORM_WEARY,
        Titles.TOO_SAFE_SAFE,
        Titles.SMOKE_WRITER_IN_THE_SKY,
        Titles.GYROS_IMAGINATION_INVENTION,
        Titles.DAY_DUCKBURG_GOT_DYED_THE,
        Titles.ROCKET_RACE_AROUND_THE_WORLD,
        Titles.BLACK_WEDNESDAY,
        Titles.KNIGHTS_OF_THE_FLYING_SLEDS,
        Titles.VILLAGE_BLACKSMITH_THE,
        Titles.BALLOONATICS,
        Titles.MISSILE_FIZZLE,
        Titles.MADCAP_MARINER_THE,
        Titles.STRANGER_THAN_FICTION,
        Titles.JET_WITCH,
        Titles.DUCKBURG_PET_PARADE_THE,
        Titles.CAPN_BLIGHTS_MYSTERY_SHIP,
        Titles.FUN_WHATS_THAT,
        Titles.ON_THE_DREAM_PLANET,
    ],
    Tags.GYRO_NOT_IN_GG: [
        Titles.HOBBLIN_GOBLINS,
        Titles.SEVEN_CITIES_OF_CIBOLA_THE,
        Titles.HEIRLOOM_WATCH,
        Titles.GLADSTONES_TERRIBLE_SECRET,
        Titles.THINK_BOX_BOLLIX_THE,
        Titles.TALKING_DOG_THE,
        Titles.WORM_WEARY,
        Titles.TOO_SAFE_SAFE,
        Titles.SMOKE_WRITER_IN_THE_SKY,
        Titles.GYROS_IMAGINATION_INVENTION,
        Titles.DAY_DUCKBURG_GOT_DYED_THE,
        Titles.ROCKET_RACE_AROUND_THE_WORLD,
        Titles.BLACK_WEDNESDAY,
        Titles.KNIGHTS_OF_THE_FLYING_SLEDS,
        Titles.UNDER_THE_POLAR_ICE,
        Titles.VILLAGE_BLACKSMITH_THE,
        Titles.BALLOONATICS,
        Titles.MISSILE_FIZZLE,
        Titles.MADCAP_MARINER_THE,
        Titles.STRANGER_THAN_FICTION,
        Titles.JET_WITCH,
        Titles.DUCKBURG_PET_PARADE_THE,
        Titles.CAPN_BLIGHTS_MYSTERY_SHIP,
        Titles.FORBIDIUM_MONEY_BIN_THE,
        # TODO: NEED TO CHECK THESE
        Titles.CALL_OF_THE_WILD_THE,
        Titles.CAVE_OF_THE_WINDS,
        Titles.MIXED_UP_MIXER,
        Titles.MADBALL_PITCHER_THE,
        Titles.BEAR_TAMER_THE,
        Titles.TALE_OF_THE_TAPE,
        Titles.HIS_SHINING_HOUR,
        Titles.THAT_SMALL_FEELING,
        Titles.YOU_CANT_WIN,
        Titles.WILY_RIVAL,
        Titles.FAST_AWAY_CASTAWAY,
        Titles.DUCKBURGS_DAY_OF_PERIL,
        Titles.GREAT_POP_UP_THE,
        Titles.MADCAP_INVENTORS,
        Titles.FINNY_FUN,
        Titles.POSTHASTY_POSTMAN,
        Titles.SNOW_DUSTER,
        Titles.HELPERS_HELPING_HAND_A,
        Titles.MAN_VERSUS_MACHINE,
        Titles.JONAH_GYRO,
        Titles.FUN_WHATS_THAT,
        Titles.ON_THE_DREAM_PLANET,
    ],
    Tags.HASSAN_BEN_JAILD: [Titles.MCDUCK_OF_ARABIA],
    Tags.HDL_DRIVING_CAR: [
        Titles.SHERIFF_OF_BULLET_VALLEY,
    ],
    Tags.HERBERT: [
        Titles.THREE_DIRTY_LITTLE_DUCKS,
        Titles.TEN_CENTS_WORTH_OF_TROUBLE,
        Titles.SMUGSNORKLE_SQUATTIE_THE,
    ],
    Tags.HIMALAYAS: [
        Titles.TRAIL_OF_THE_UNICORN,
        Titles.TRALLA_LA,
        Titles.LOST_CROWN_OF_GENGHIS_KHAN_THE,
    ],
    Tags.HONDORICA: [
        Titles.SECRET_OF_HONDORICA,
        Titles.TERRIBLE_TOURIST,
    ],
    Tags.HYPNOSIS: [
        Titles.DAYS_AT_THE_LAZY_K,
        Titles.ADVENTURE_DOWN_UNDER,
        Titles.GOING_APE,
        Titles.YOU_CANT_GUESS,
        Titles.HYPNO_GUN_THE,
        Titles.BACK_TO_LONG_AGO,
        Titles.LOST_PEG_LEG_MINE_THE,
        Titles.RAVEN_MAD,
        Titles.THRIFTY_SPENDTHRIFT_THE,
        Titles.SWAMP_OF_NO_RETURN_THE,
    ],
    Tags.INDIA: [
        Titles.MAHARAJAH_DONALD,
        Titles.TRAIL_OF_THE_UNICORN,
        Titles.MINES_OF_KING_SOLOMON_THE,
        Titles.BILLION_DOLLAR_SAFARI_THE,
        Titles.ROCKET_RACE_AROUND_THE_WORLD,
    ],
    Tags.INDIAN_OCEAN: [
        Titles.MANY_FACES_OF_MAGICA_DE_SPELL_THE,
        Titles.DOOM_DIAMOND_THE,
    ],
    Tags.INDO_CHINA: [
        Titles.CITY_OF_GOLDEN_ROOFS,
        Titles.MCDUCK_OF_ARABIA,
        Titles.TREASURE_OF_MARCO_POLO,
        Titles.MONKEY_BUSINESS,
    ],
    Tags.INUIT: [
        Titles.FROZEN_GOLD,
        Titles.LUCK_OF_THE_NORTH,
    ],
    Tags.IRAQ: [
        Titles.FABULOUS_PHILOSOPHERS_STONE_THE,
        Titles.RUG_RIDERS_IN_THE_SKY,
    ],
    Tags.ISOTOPES: [Titles.SUPER_SNOOPER],
    Tags.ITALY: [
        Titles.FABULOUS_PHILOSOPHERS_STONE_THE,
        Titles.MIDAS_TOUCH_THE,
        Titles.UNSAFE_SAFE_THE,
        Titles.ODDBALL_ODYSSEY,
        Titles.FOR_OLD_DIMES_SAKE,
        Titles.MANY_FACES_OF_MAGICA_DE_SPELL_THE,
        Titles.DUCKS_EYE_VIEW_OF_EUROPE_A,
    ],
    Tags.ITSA_FAKA: [Titles.IN_ANCIENT_PERSIA],
    Tags.JAYNE_GIRLSFIELD: [Titles.SITTING_HIGH],
    Tags.JIVARO: [Titles.MONEY_CHAMP_THE],
    Tags.JUGHEAD_JONES: [Titles.OUTFOXED_FOX],
    Tags.JUNIOR_WOODCHUCKS: [
        Titles.OPERATION_ST_BERNARD,
        Titles.TEN_STAR_GENERALS,
        Titles.GLADSTONES_USUAL_VERY_GOOD_YEAR,
        Titles.SCREAMING_COWBOY_THE,
        Titles.SPENDING_MONEY,
        Titles.MY_LUCKY_VALENTINE,
        Titles.BEE_BUMBLES,
        Titles.CHICKADEE_CHALLENGE_THE,
        Titles.HALF_BAKED_BAKER_THE,
        Titles.TRACKING_SANDY,
        Titles.BLACK_FOREST_RESCUE_THE,
        Titles.STUBBORN_STORK_THE,
        Titles.UNDER_THE_POLAR_ICE,
        Titles.DOG_SITTER_THE,
        Titles.HOUND_HOUNDER,
        Titles.MEDALING_AROUND,
        Titles.BEACH_BOY,
        Titles.BUBBLEWEIGHT_CHAMP,
    ],
    Tags.J_MORGANBILT_GILTWHISKERS: [Titles.WIRED],
    Tags.KAKIMAW_INDIANS: [Titles.IN_KAKIMAW_COUNTRY],
    Tags.KAKIMAW_COUNTRY: [Titles.IN_KAKIMAW_COUNTRY],
    Tags.LABRADOR: [Titles.GOLDEN_HELMET_THE],
    Tags.LIBYA: [Titles.ROCKET_RACE_AROUND_THE_WORLD],
    Tags.LITHIUM: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.LONGHORN_TALLGRASS: [Titles.FABULOUS_TYCOON_THE],
    Tags.MAD_SCIENTIST: [Titles.IN_ANCIENT_PERSIA],
    Tags.MAGIC: [Titles.MAGICAL_MISERY],
    Tags.MAGICA_DE_SPELL: [
        Titles.MIDAS_TOUCH_THE,
        Titles.UNSAFE_SAFE_THE,
        Titles.ODDBALL_ODYSSEY,
        Titles.FOR_OLD_DIMES_SAKE,
        Titles.ISLE_OF_GOLDEN_GEESE,
        Titles.MANY_FACES_OF_MAGICA_DE_SPELL_THE,
        Titles.RUG_RIDERS_IN_THE_SKY,
        Titles.TEN_CENT_VALENTINE,
        Titles.RAVEN_MAD,
    ],
    Tags.MALI: [
        Titles.DAY_DUCKBURG_GOT_DYED_THE,
        Titles.CANDY_KID_THE,
    ],
    Tags.MANGANESE: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.MERCURY: [Titles.FABULOUS_PHILOSOPHERS_STONE_THE],
    Tags.MISSISSIPPI: [Titles.TERROR_OF_THE_RIVER_THE],
    Tags.MONGOLIA: [Titles.MONEY_CHAMP_THE],
    Tags.MOROCCO: [Titles.MAGIC_HOURGLASS_THE],
    Tags.MOURNFUL_MARY: [Titles.ADVENTURE_DOWN_UNDER],
    Tags.MR_MC_SWINE: [Titles.MILKMAN_THE],
    Tags.NAPHTHA: [Titles.LOVELORN_FIREMAN_THE],
    Tags.NEIGHBOR_JONES: [
        Titles.GOOD_DEEDS,
        Titles.GOOD_NEIGHBORS,
        Titles.PURLOINED_PUTTY_THE,
        Titles.TEN_DOLLAR_DITHER,
        Titles.SILENT_NIGHT,
        Titles.GOOD_DEEDS_THE,
        Titles.FEUD_AND_FAR_BETWEEN,
        Titles.UNFRIENDLY_ENEMIES,
    ],
    Tags.NEUTRON: [Titles.DANGEROUS_DISGUISE],
    Tags.NEWFOUNDLAND: [Titles.GOLDEN_HELMET_THE],
    Tags.NEW_VERSIONS: [
        Titles.MOCKING_BIRD_RIDGE,
        Titles.DRAMATIC_DONALD,
        Titles.LITTLEST_CHICKEN_THIEF_THE,
        Titles.BEACHCOMBERS_PICNIC_THE,
        Titles.GOOD_DEEDS_THE,
        Titles.WATCHFUL_PARENTS_THE,
        Titles.WANT_TO_BUY_AN_ISLAND,
        Titles.FROGGY_FARMER,
        Titles.ICE_TAXIS_THE,
        Titles.IN_THE_SWIM,
        Titles.ROCKET_RACE_AROUND_THE_WORLD,
        Titles.TERRIBLE_TOURIST,
        Titles.LAND_OF_THE_PYGMY_INDIANS,
        Titles.FORBIDDEN_VALLEY,
        Titles.YOICKS_THE_FOX,
    ],
    Tags.NIAGARA_FALLS: [Titles.HIGH_WIRE_DAREDEVILS],
    Tags.NICKEL: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.NITROGEN: [Titles.MAD_CHEMIST_THE],
    Tags.NITROGLYCERIN: [Titles.JAM_ROBBERS, Titles.ROCKET_RACE_TO_THE_MOON],
    Tags.NORWAY: [Titles.LEMMING_WITH_THE_LOCKET_THE],
    Tags.NOSUCHIUM: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.OHIO: [Titles.TERROR_OF_THE_RIVER_THE],
    Tags.OLD_DEMON_TOOTH: [Titles.GOLDEN_CHRISTMAS_TREE_THE, Titles.MONEY_STAIRS_THE],
    Tags.OPA: [Titles.MAD_CHEMIST_THE],
    Tags.OXYGEN: [Titles.GOLDEN_HELMET_THE, Titles.TRALLA_LA, Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.PAKISTAN: [Titles.LOST_CROWN_OF_GENGHIS_KHAN_THE],
    Tags.PEEWEEGAH_INDIANS: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.PERSIA: [Titles.IN_ANCIENT_PERSIA],
    Tags.PERU: [Titles.LOST_IN_THE_ANDES],
    Tags.PETER_SCHILLING_FAVOURITES: [
        # This list of the Barks stories covered in Peter Schilling's book:
        # "Carl Barks' Duck - Average American"
        Titles.MAHARAJAH_DONALD,
        Titles.LOST_IN_THE_ANDES,
        Titles.LUCK_OF_THE_NORTH,
        Titles.GILDED_MAN_THE,
        Titles.MAGIC_HOURGLASS_THE,
        Titles.GOLDEN_HELMET_THE,
        Titles.LAND_OF_THE_TOTEM_POLES,
        Titles.NO_SUCH_VARMINT,
        Titles.MASTER_RAINMAKER_THE,
        Titles.SMOKE_WRITER_IN_THE_SKY,
        Titles.MASTER_GLASSER_THE,
        Titles.SPARE_THAT_HAIR,
        Titles.VACATION_TIME,
    ],
    Tags.PHOSPHORUS: [Titles.KRANKENSTEIN_GYRO],
    Tags.PLAIN_AWFUL: [Titles.LOST_IN_THE_ANDES],
    Tags.PLASMA: [Titles.KRANKENSTEIN_GYRO],
    Tags.PLATINUM: [
        Titles.LAND_OF_THE_PYGMY_INDIANS,
        Titles.RICHES_RICHES_EVERYWHERE,
        Titles.STATUESQUE_SPENDTHRIFTS,
    ],
    Tags.PORKMAN_DE_LARDO: [Titles.STATUS_SEEKER_THE],
    Tags.POTASH: [Titles.KRANKENSTEIN_GYRO],
    Tags.PULPHEART_CLABBERHEAD: [Titles.SPOIL_THE_ROD],
    Tags.P_J_MC_BRINE: [Titles.FORBIDDEN_VALLEY],
    Tags.RUSSIA: [Titles.CITY_OF_GOLDEN_ROOFS],
    Tags.SCOTLAND: [
        Titles.OLD_CASTLES_SECRET_THE,
        Titles.HOUND_OF_THE_WHISKERVILLES,
        Titles.INVISIBLE_INTRUDER_THE,
        Titles.MYSTERY_OF_THE_LOCH,
    ],
    Tags.SCROOGE_NOT_IN_US: [
        Titles.CHRISTMAS_ON_BEAR_MOUNTAIN,
        Titles.OLD_CASTLES_SECRET_THE,
        Titles.FOXY_RELATIONS,
        Titles.SUNKEN_YACHT_THE,
        Titles.RACE_TO_THE_SOUTH_SEAS,
        Titles.VOODOO_HOODOO,
        Titles.LETTER_TO_SANTA,
        Titles.TRAIL_OF_THE_UNICORN,
        Titles.PIXILATED_PARROT_THE,
        Titles.MAGIC_HOURGLASS_THE,
        Titles.YOU_CANT_GUESS,
        Titles.NO_SUCH_VARMINT,
        Titles.BILLIONS_TO_SNEEZE_AT,
        Titles.FINANCIAL_FABLE_A,
        Titles.TROUBLE_WITH_DIMES_THE,
        Titles.CHRISTMAS_FOR_SHACKTOWN_A,
        Titles.TERROR_OF_THE_BEAGLE_BOYS,
        Titles.BIG_BIN_ON_KILLMOTOR_HILL_THE,
        Titles.STATUESQUE_SPENDTHRIFTS,
        Titles.GLADSTONES_TERRIBLE_SECRET,
        Titles.SPENDING_MONEY,
        Titles.HYPNO_GUN_THE,
        Titles.TURKEY_WITH_ALL_THE_SCHEMINGS,
        Titles.SOME_HEIR_OVER_THE_RAINBOW,
        Titles.MONEY_STAIRS_THE,
        Titles.WISPY_WILLIE,
        Titles.TURKEY_TROT_AT_ONE_WHISTLE,
        Titles.FLOUR_FOLLIES,
        Titles.TOO_SAFE_SAFE,
        Titles.SEARCH_FOR_THE_CUSPIDORIA,
        Titles.SECRET_OF_HONDORICA,
        Titles.TROUBLE_INDEMNITY,
        Titles.SEARCHING_FOR_A_SUCCESSOR,
        Titles.SMOKE_WRITER_IN_THE_SKY,
        Titles.RUNAWAY_TRAIN_THE,
        Titles.IN_KAKIMAW_COUNTRY,
        Titles.LOST_PEG_LEG_MINE_THE,
        Titles.SAGMORE_SPRINGS_HOTEL,
        Titles.TENDERFOOT_TRAP_THE,
        Titles.BLACK_PEARLS_OF_TABU_YAMA_THE,
        Titles.SEPTEMBER_SCRIMMAGE,
        Titles.TITANIC_ANTS_THE,
        Titles.MOCKING_BIRD_RIDGE,
        Titles.FORBIDIUM_MONEY_BIN_THE,
        Titles.TRACKING_SANDY,
        Titles.FLOATING_ISLAND_THE,
        Titles.BLACK_WEDNESDAY,
        Titles.FUN_WHATS_THAT,
        Titles.STUBBORN_STORK_THE,
        Titles.CAVE_OF_THE_WINDS,
        Titles.VILLAGE_BLACKSMITH_THE,
        Titles.ROCKS_TO_RICHES,
        Titles.MADCAP_MARINER_THE,
        Titles.MR_PRIVATE_EYE,
        Titles.BOAT_BUSTER,
        Titles.TEN_CENT_VALENTINE,
        Titles.RAVEN_MAD,
        Titles.MATTER_OF_FACTORY_A,
        Titles.CHRISTMAS_CHEERS,
        Titles.ZERO_HERO,
        Titles.DUCKBURG_PET_PARADE_THE,
        Titles.DOUBLE_MASQUERADE,
        Titles.DELIVERY_DILEMMA,
    ],
    Tags.SELENIUM: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.SOAPY_SLICK: [Titles.NORTH_OF_THE_YUKON],
    Tags.SOUTH_AFRICA: [
        Titles.SECOND_RICHEST_DUCK_THE,
        Titles.SO_FAR_AND_NO_SAFARI,
    ],
    Tags.SPAIN: [
        Titles.DANGEROUS_DISGUISE,
        Titles.ROCKET_RACE_AROUND_THE_WORLD,
    ],
    Tags.SQUARE_EGGS: [Titles.LOST_IN_THE_ANDES],
    Tags.STICKAREE_INDIANS: [Titles.FORBIDDEN_VALLEY],
    Tags.STROMBOLIUM: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.SUDAN: [Titles.MINES_OF_KING_SOLOMON_THE],
    Tags.SULPHUR: [
        Titles.MAD_CHEMIST_THE,
        Titles.DANGEROUS_DISGUISE,
        Titles.FABULOUS_PHILOSOPHERS_STONE_THE,
        Titles.FANTASTIC_RIVER_RACE_THE,
        Titles.GOPHER_GOOF_UPS,
        Titles.LOVELORN_FIREMAN_THE,
        Titles.KRANKENSTEIN_GYRO,
    ],
    Tags.SULPHURIC_ACID: [Titles.BIG_BIN_ON_KILLMOTOR_HILL_THE],
    Tags.SWEDEN: [Titles.MINES_OF_KING_SOLOMON_THE],
    Tags.SWITZERLAND: [Titles.DUCKS_EYE_VIEW_OF_EUROPE_A],
    Tags.SYDNEY: [Titles.ADVENTURE_DOWN_UNDER],
    Tags.SYRIA: [Titles.FABULOUS_PHILOSOPHERS_STONE_THE],
    Tags.TANGANYIKA: [Titles.UNSAFE_SAFE_THE],
    Tags.TANGKOR_WAT: [Titles.CITY_OF_GOLDEN_ROOFS],
    Tags.TANTALUM: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.TERRIES: [Titles.LAND_BENEATH_THE_GROUND],
    Tags.THORIUM: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.WEEMITE: [Titles.ROCKET_ROASTED_CHRISTMAS_TURKEY],
    Tags.WHATTISIUM: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.WIKI_NOTABLE_STORIES: [
        Titles.DONALD_DUCK_FINDS_PIRATE_GOLD,
        Titles.DONALD_DUCK_AND_THE_MUMMYS_RING,
        Titles.CHRISTMAS_ON_BEAR_MOUNTAIN,
        Titles.OLD_CASTLES_SECRET_THE,
        Titles.SHERIFF_OF_BULLET_VALLEY,
        Titles.LOST_IN_THE_ANDES,
        Titles.VACATION_TIME,
        Titles.FINANCIAL_FABLE_A,
        Titles.IN_OLD_CALIFORNIA,
        Titles.CHRISTMAS_FOR_SHACKTOWN_A,
        Titles.ONLY_A_POOR_OLD_MAN,
        Titles.FLIP_DECISION,
        Titles.GOLDEN_HELMET_THE,
        Titles.BACK_TO_THE_KLONDIKE,
        Titles.TRALLA_LA,
        Titles.FABULOUS_PHILOSOPHERS_STONE_THE,
        Titles.GOLDEN_FLEECING_THE,
        Titles.LAND_BENEATH_THE_GROUND,
        Titles.MONEY_WELL_THE,
        Titles.GOLDEN_RIVER_THE,
        Titles.ISLAND_IN_THE_SKY,
        Titles.NORTH_OF_THE_YUKON,
    ],
    Tags.WOLFRAMITE: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.WORRY_ROOM: [
        Titles.SECRET_OF_ATLANTIS_THE,
        Titles.LAND_BENEATH_THE_GROUND,
        Titles.MONEY_WELL_THE,
        Titles.COLOSSALEST_SURPRISE_QUIZ_SHOW_THE,
        Titles.PAUL_BUNYAN_MACHINE_THE,
        Titles.HOUSE_OF_HAUNTS,
    ],
    Tags.YOUGUESSIUM: [Titles.LAND_OF_THE_PYGMY_INDIANS],
    Tags.ZINC: [Titles.KRANKENSTEIN_GYRO],
    Tags.ZIRCONIUM: [Titles.LAND_OF_THE_PYGMY_INDIANS],
}

BARKS_TAGGED_PAGES: dict[tuple[Tags, Titles], list[str]] = {
    (Tags.ALASKA, Titles.BACK_TO_THE_KLONDIKE): ["7"],
    (Tags.ALKALI, Titles.TWENTY_FOUR_CARAT_MOON_THE): ["11"],
    (Tags.APPLECHEEKS_TEENGIGGLE, Titles.PERSISTENT_POSTMAN_THE): ["2"],
    (Tags.AUSTRALIAN_ABORIGINALS, Titles.ADVENTURE_DOWN_UNDER): [
        "7",
        "13",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
    ],
    (Tags.AWFULTONIANS, Titles.LOST_IN_THE_ANDES): [
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "26",
        "27",
        "28",
        "29",
        "31",
    ],
    (Tags.BAGDAD, Titles.FABULOUS_PHILOSOPHERS_STONE_THE): ["8"],
    (Tags.BARNACLE_BAY, Titles.NO_SUCH_VARMINT): ["11"],
    (Tags.BOP_BOP, Titles.VOODOO_HOODOO): ["1"],
    (Tags.BRITISH_GUIANA, Titles.GILDED_MAN_THE): ["8"],
    (Tags.CABBAGE_PROFESSOR, Titles.MYSTERIOUS_STONE_RAY_THE): [
        "20",
        "21",
        "22",
        "23",
        "24",
        "26",
        "27",
        "28",
    ],
    (Tags.CALCIUM, Titles.KRANKENSTEIN_GYRO): ["1"],
    (Tags.CAMERAS, Titles.SECRET_RESOLUTIONS): ["8"],
    (Tags.CAMERAS, Titles.VACATION_TIME): ["10"],  # plus more pages
    (Tags.CANADA, Titles.FROZEN_GOLD): ["4"],
    (Tags.CARBON, Titles.TWENTY_FOUR_CARAT_MOON_THE): ["19"],
    (Tags.CARVER_BEAKOFF, Titles.FIREBUG_THE): ["13"],
    (Tags.CAR_313, Titles.DONALDS_MONSTER_KITE): ["7", "8", "9", "10"],
    (Tags.CAR_313, Titles.MAD_CHEMIST_THE): ["2", "3", "5", "6"],
    (Tags.CAR_313, Titles.RIP_VAN_DONALD): ["6", "7", "8", "9", "10"],
    (Tags.CAR_313, Titles.SHERIFF_OF_BULLET_VALLEY): ["1", "3", "11", "12", "14"],
    (Tags.CAR_313, Titles.VOLCANO_VALLEY): ["2"],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.BILL_COLLECTORS_THE): ["3"],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.BONGO_ON_THE_CONGO): ["2", "4", "5", "6", "7", "8"],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.FIREBUG_THE): ["13"],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.FROZEN_GOLD): ["5", "9", "16", "17", "24"],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.GOLDEN_FLEECING_THE): [
        "6",
        "7",
        "9",
        "13",
        "14",
        "15",
        "16",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
    ],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.ICEBOX_ROBBER_THE): ["7"],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.LOST_IN_THE_ANDES): [
        "20",
        "21",
        "22",
        "23",
        "24",
        "26",
        "27",
        "28",
        "29",
        "31",
    ],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.LOVELORN_FIREMAN_THE): ["8"],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.SWIMMING_SWINDLERS): ["1", "2", "7"],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.TERROR_OF_THE_RIVER_THE): ["1"],
    (Tags.CENSORED_STORIES_BUT_FIXED, Titles.VOODOO_HOODOO): [
        "1",
        "6",
        "8",
        "9",
        "10",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "20",
        "22",
        "23",
        "31",
        "32",
    ],
    (Tags.CHEMICAL_FORMULA, Titles.BEAR_TAMER_THE): ["4", "5"],
    (Tags.CHEMICAL_FORMULA, Titles.MAD_CHEMIST_THE): ["1", "2"],
    (Tags.CHEMICAL_FORMULA, Titles.MIXED_UP_MIXER): ["3"],
    (Tags.CHEMICAL_FORMULA, Titles.PIED_PIPER_OF_DUCKBURG_THE): ["2"],
    (Tags.CIGARETTES, Titles.BILLIONS_TO_SNEEZE_AT): ["8"],
    (Tags.CIGARETTES, Titles.DANGEROUS_DISGUISE): ["3"],
    (Tags.CIGARETTES, Titles.GOING_BUGGY): ["3"],
    (Tags.CIGARETTES, Titles.JAM_ROBBERS): ["7"],
    (Tags.CIGARETTES, Titles.MAD_CHEMIST_THE): ["10"],
    (Tags.CIGARETTES, Titles.SHERIFF_OF_BULLET_VALLEY): [
        "4",
        "5",
        "6",
        "8",
        "13",
        "14",
        "17",
        "20",
        "25",
        "26",
        "27",
    ],
    (Tags.CIGARETTES, Titles.SWIMMING_SWINDLERS): ["1", "2", "7"],
    (Tags.CIGARETTES, Titles.VACATION_TIME): ["8", "9", "12", "13", "29", "30"],
    (Tags.COLUMBIUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["23"],
    (Tags.COPPER, Titles.FABULOUS_PHILOSOPHERS_STONE_THE): ["1"],
    (Tags.COPPER, Titles.GOLD_FINDER_THE): ["1"],
    (Tags.COPPER, Titles.LAND_OF_THE_PYGMY_INDIANS): ["5"],
    (Tags.COPPER, Titles.ONLY_A_POOR_OLD_MAN): ["8", "22"],
    (Tags.COPPER, Titles.RICHES_RICHES_EVERYWHERE): ["14"],
    (Tags.CORNELIUS_MC_COBB, Titles.VOODOO_HOODOO): ["20", "21", "22", "23"],
    (Tags.CRETE, Titles.FABULOUS_PHILOSOPHERS_STONE_THE): ["9"],
    (Tags.DAISY, Titles.EYES_IN_THE_DARK): ["7"],
    (Tags.DAMASCUS, Titles.FABULOUS_PHILOSOPHERS_STONE_THE): ["8"],
    (Tags.DUCKMITE, Titles.MAD_CHEMIST_THE): ["2", "3", "4", "5", "6", "10"],
    (Tags.EL_DORADO, Titles.GILDED_MAN_THE): [
        "8",
        "11",
        "12",
        "14",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
    ],
    (Tags.FLORIDA, Titles.CHARITABLE_CHORE_A): ["6"],
    (Tags.FOOLA_ZOOLA, Titles.VOODOO_HOODOO): [
        "6",
        "17",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "29",
        "30",
        "31",
    ],
    (Tags.FORBIDIUM, Titles.FORBIDIUM_MONEY_BIN_THE): ["1", "4", "10", "11"],
    (Tags.GYRO_NOT_IN_GG, Titles.KNIGHTS_OF_THE_FLYING_SLEDS): ["3"],
    (Tags.GYRO_NOT_IN_GG, Titles.UNDER_THE_POLAR_ICE): ["3"],
    (Tags.HDL_DRIVING_CAR, Titles.SHERIFF_OF_BULLET_VALLEY): ["11", "12", "14"],
    (Tags.HONDORICA, Titles.SECRET_OF_HONDORICA): ["1"],
    (Tags.HONDORICA, Titles.TERRIBLE_TOURIST): ["1", "7", "10"],
    (Tags.INUIT, Titles.FROZEN_GOLD): ["16", "17"],
    (Tags.INUIT, Titles.LUCK_OF_THE_NORTH): ["14"],
    (Tags.ISOTOPES, Titles.SUPER_SNOOPER): ["4"],
    (Tags.ITSA_FAKA, Titles.IN_ANCIENT_PERSIA): ["6", "10", "12", "19", "20", "23"],
    (Tags.JAYNE_GIRLSFIELD, Titles.SITTING_HIGH): ["1", "2"],
    (Tags.JIVARO, Titles.MONEY_CHAMP_THE): ["15", "16", "17", "19", "20", "21", "22"],
    (Tags.JUGHEAD_JONES, Titles.OUTFOXED_FOX): ["2", "4"],
    (Tags.J_MORGANBILT_GILTWHISKERS, Titles.WIRED): ["10"],
    (Tags.LABRADOR, Titles.GOLDEN_HELMET_THE): ["5", "6", "9", "10"],
    (Tags.LITHIUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["22"],
    (Tags.MALI, Titles.DAY_DUCKBURG_GOT_DYED_THE): ["10"],
    (Tags.MANGANESE, Titles.LAND_OF_THE_PYGMY_INDIANS): ["5"],
    (Tags.MERCURY, Titles.FABULOUS_PHILOSOPHERS_STONE_THE): ["2"],
    (Tags.MISSISSIPPI, Titles.TERROR_OF_THE_RIVER_THE): ["16"],
    (Tags.MOURNFUL_MARY, Titles.ADVENTURE_DOWN_UNDER): [
        "8",
        "9",
        "10",
        "11",
        "12",
        "15",
        "17",
        "22",
        "23",
        "24",
    ],
    (Tags.NAPHTHA, Titles.LOVELORN_FIREMAN_THE): ["3"],
    (Tags.NEIGHBOR_JONES, Titles.GOOD_DEEDS): ["1"],
    (Tags.NEUTRON, Titles.DANGEROUS_DISGUISE): ["27"],
    (Tags.NEWFOUNDLAND, Titles.GOLDEN_HELMET_THE): ["9", "11", "23"],
    (Tags.NICKEL, Titles.LAND_OF_THE_PYGMY_INDIANS): ["2", "5", "19"],
    (Tags.NITROGEN, Titles.MAD_CHEMIST_THE): ["2"],
    (Tags.NITROGLYCERIN, Titles.JAM_ROBBERS): ["8", "9"],
    (Tags.NITROGLYCERIN, Titles.ROCKET_RACE_TO_THE_MOON): ["8"],
    (Tags.NOSUCHIUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["24"],
    (Tags.OHIO, Titles.TERROR_OF_THE_RIVER_THE): ["4"],
    (Tags.OPA, Titles.MAD_CHEMIST_THE): ["1"],
    (Tags.OXYGEN, Titles.GOLDEN_HELMET_THE): ["28"],
    (Tags.OXYGEN, Titles.LAND_OF_THE_PYGMY_INDIANS): ["27"],
    (Tags.OXYGEN, Titles.TRALLA_LA): ["8"],
    (Tags.PHOSPHORUS, Titles.KRANKENSTEIN_GYRO): ["1"],
    (Tags.PLASMA, Titles.KRANKENSTEIN_GYRO): ["1"],
    (Tags.PLATINUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["5"],
    (Tags.PLATINUM, Titles.RICHES_RICHES_EVERYWHERE): ["14"],
    (Tags.PLATINUM, Titles.STATUESQUE_SPENDTHRIFTS): ["9"],
    (Tags.POTASH, Titles.KRANKENSTEIN_GYRO): ["1"],
    (Tags.P_J_MC_BRINE, Titles.FORBIDDEN_VALLEY): ["3"],
    (Tags.SELENIUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["22"],
    (Tags.STICKAREE_INDIANS, Titles.FORBIDDEN_VALLEY): [
        "8",
        "9",
        "11",
        "13",
        "15",
        "16",
        "17",
        "18",
        "24",
    ],
    (Tags.STROMBOLIUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["24", "27"],
    (Tags.SULPHUR, Titles.DANGEROUS_DISGUISE): ["27"],
    (Tags.SULPHUR, Titles.FABULOUS_PHILOSOPHERS_STONE_THE): ["2"],
    (Tags.SULPHUR, Titles.FANTASTIC_RIVER_RACE_THE): ["8"],
    (Tags.SULPHUR, Titles.GOPHER_GOOF_UPS): ["2", "3"],
    (Tags.SULPHUR, Titles.KRANKENSTEIN_GYRO): ["1"],
    (Tags.SULPHUR, Titles.LOVELORN_FIREMAN_THE): ["3"],
    (Tags.SULPHUR, Titles.MAD_CHEMIST_THE): ["1", "2"],
    (Tags.SULPHURIC_ACID, Titles.BIG_BIN_ON_KILLMOTOR_HILL_THE): ["3"],
    (Tags.TANGKOR_WAT, Titles.CITY_OF_GOLDEN_ROOFS): ["17"],
    (Tags.TANTALUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["24"],
    (Tags.THORIUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["22"],
    (Tags.WEEMITE, Titles.ROCKET_ROASTED_CHRISTMAS_TURKEY): ["3", "4", "6", "7", "8"],
    (Tags.WHATTISIUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["23"],
    (Tags.WOLFRAMITE, Titles.LAND_OF_THE_PYGMY_INDIANS): ["5"],
    (Tags.WORRY_ROOM, Titles.COLOSSALEST_SURPRISE_QUIZ_SHOW_THE): ["3"],
    (Tags.WORRY_ROOM, Titles.HOUSE_OF_HAUNTS): ["3"],
    (Tags.WORRY_ROOM, Titles.LAND_BENEATH_THE_GROUND): ["1"],
    (Tags.WORRY_ROOM, Titles.MONEY_WELL_THE): ["4"],
    (Tags.WORRY_ROOM, Titles.PAUL_BUNYAN_MACHINE_THE): ["6", "8"],
    (Tags.WORRY_ROOM, Titles.SECRET_OF_ATLANTIS_THE): ["1"],
    (Tags.YOUGUESSIUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["24"],
    (Tags.ZINC, Titles.KRANKENSTEIN_GYRO): ["1"],
    (Tags.ZIRCONIUM, Titles.LAND_OF_THE_PYGMY_INDIANS): ["23"],
}
