from barks_fantagraphics.barks_words import US_STATES

TERMS_TO_REMOVE: set[str] = {
    "_",
}

# noinspection SpellCheckingInspection
BARKSIAN_FULL_NAMES: set[str] = {
    "Benzine Banzoony",
    "Bey of El Dagga",
    "Black Mariah",
    "Casaba Cantaloupa",
    "Chisel McSue",
    "Daredevil Daly",
    "Diamond Dick",
    "Doctor Thinknoble",
    "Don Gaspar",
    "Don Porko de Lardo",
    "Porko de Lardo",
    "Don Quixote",
    "Dr. U. Qwik",
    "Falcon Rover",
    "Finnan Haddie",
    "Flintheart Glomgold",
    "Francisco de Ulloa",
    "Fulldrip Pulpbugle",
    "General Snozzie",
    "Genghis Khan",
    "Ghaspan Ghulp Plateau",
    "Great Thunderface",
    "Great Rain-in-Teepee",
    "Heston Froster",
    "Horseshoe Hogg",
    "Jim Dandy",
    "John the Junkman",
    "Jolly Roger",
    "Jughead Jones's",
    "King Croesus",
    "King Solomon",
    "Lubricated Lightning",
    "Manana N. de Patio",
    "Mesmer J. Spellcaster",
    "Mousie Mona from Corona",
    "Needle Nose",
    "Olaf the Blue",
    "Perry Cougar",
    "Philo T. Ellic",
    "Porkmuscle J. Hamfat",
    "Prof. Batty",
    "Prof. Brainwhiz",
    "Prof. Blabaway Utterbunk",
    "Prof. Utterbunk",
    "Prof. Missilebug",
    "Queen of the Kangaroos",
    "Queen of Seiprah",
    "Queen Bess",
    "Queen Mary",
    "Queen Veronica",
    "Queen Victoria's",
    "Ramrod Ransom",
    "Reggie de Pyster",
    "Rodney McHowl",
    "Santa Claus",
    "Senator Snoggin",
    "Smoked Barracuda",
    "Sir Galahad",
    "St. George",
    "Trestleman Truckhorse",
    "Trigger Trueshot",
    "Unca Donald",
    "Uncle Donald",
    "Unca Scrooge",
    "Uncle Scrooge",
    "Whirlman Dervish",
    "Wild Bill Carson",
    "Wild Bill Trueshot",
}

# noinspection SpellCheckingInspection
BARKSIAN_PLACES_FULL_NAMES: set[str] = {
    "Ancient Bengali",
    "Ancient Cathay",
    "Ancient Egyptian",
    "Barnacle Bay",
    "Beavertail Lake",
    "Brown Derby",
    "Cape Sourweather",
    "Codfish Cove",
    "Columbia River",
    "Cornpone Gables",
    "Darkest Africa",
    "Dayton Street",
    "El Dorado",
    "Fisherman's Pier",
    "Frostbite on the Chillblain",
    "Gneezle Gnob",
    "Hag's Fang Cliff",
    "Isle of Capri",
    "Jugneck Cove",
    "Laguna Mountains",
    "Lost Dutchman's",
    "Lower California",
    "Mt. Mushmore",
    "New Caledonia",
    "New Guinea",
    "North America",
    "Palo Casaba",
    "Pizen Valley",
    "Sagmore Springs",
    "San Antone",
    "San Diego",
    "San Jac",
    "San Joaquin Valley",
    "Smugglers' Roost",
    "Snarling Rocks Bay",
    "South Orkney Islands",
    "Sutter's Fort",
    "Tabu Yama",
    "Thrushwistle Glen",
    "Tulebug River",
    "Upper Whambesi",
    "Vale of Kashmir",
}

# noinspection SpellCheckingInspection
BARKSIAN_THINGS_FULL_NAMES: set[str] = {
    "Belgian Prince Leopold",
    "Bungling Bros Circus",
    "Casa del Hoosier Motel",
    "cat-o'-nine-tails",
    "Cotton Queen",
    "Eager Edgars",
    "Lobster NewbUrg",
    "Quackly Hall",
    "Ramona Pageant Bowl",
    "River Belle",
    "Squanderbilt Hotel",
    "Worry Room",
}

# TODO: Maybe put these in map?
# noinspection SpellCheckingInspection
BARKSIAN_TITLES: set[str] = {
    "Alice in Wonderland",
    "Blistering Bullets",
    "Bullet Pizen At Rustlers' Gallows",
    "Carnage on the Cimarron",
    "Fagin's Fangs",
    "Feebrunkle's Fix-it Guide",
    "Ghost of the Gunnison",
    "Gore in the Gully",
    "Gory Gap",
    "Gunsmoke Gulch",
    "Gunfire on the Rio",
    "Law of the Roaring Winchesters",
    "Powderburns on the Powderhorn",
    "Sagebrush Savage",
    "Search for Murphy's Bridie",
    "Wonderhead Son of Ticka",
}

# noinspection SpellCheckingInspection
BARKSIAN_MISC_FULL_NAMES: set[str] = {
    "Blue Danube",
    "Blue Danube Waltz",
    "Brahms Concerto",
}

# noinspection SpellCheckingInspection
NAME_MAP: dict[str, str] = {
    "almostus": "Almostus Extinctus",
    "extinctus": "Almostus Extinctus",
    "extinctuses": "Almostus Extinctuses",
    "angeles": "Los Angeles",
    "los": "Los Angeles",
    "antone": "San Antone",
    "applecheeks": "Applecheeks Teengiggle",
    "b-197": "B-197 X-NG",
    "x-ng": "B-197 X-NG",
    "b-boys": "B-Boys",
    "b-boys'": "B-Boys'",
    "bhagi-bhreeches": "Bhagi-Bhreeches",
    "boer": "Boer War",
    "brookside": "Brookside Park",
    "cattail": "Cattail Slough",
    "chillspine": "Chillspine Buoy",
    "codfeesh": "Codfeesh Cove",
    "coney": "Coney Island",
    "costa": "Costa Rica",
    "crack-in-cloud": "Crack-in-Cloud",
    "creole": "Creole Belle",
    "crepe": "Crepe Suzettes",
    "suzettes": "Crepe Suzettes",
    "crooge": "Scrooge",  # TODO: Hack to handle '$crooge'
    "daniel": "Daniel Boone",
    "debbies": "Junior Sub-teen-age Debbies Club",
    "donna": "Donna Duck",
    "ele-phant": "elephant",
    "fe": "Santa Fe",
    "frozenbear": "Frozenbear Lake",
    "hagtooth": "Hagtooth Rock",
    "indo-china": "Indo-China",
    "lazy-k": "Lazy-K",
    "mc-who": "Mc-Who",
    "mammalarius": "Mammalarius Aquapodicus",
    "mcbray": "McBray",
    "mcbrine": "McBrine",
    "mcbrine's": "McBrine's",
    "mccann's": "McCann's",
    "mcchain": "McChain",
    "mcarchives": "McArchives",
    "mcchicken": "McChicken",
    "mccobb": "McCobb",
    "mccornburger's": "McCornburger's",
    "mccoy": "McCoy",
    "mccrow": "McCrow",
    "mcdock": "McDock",
    "mcdome": "McDome",
    "mcduck": "McDuck",
    "mcduck's": "McDuck's",
    "mcducks": "McDucks",
    "mceagle": "McEagle",
    "mceye": "McEye",
    "mcfiendy": "McFiendy",
    "mcgillicuddy": "McGillicuddy",
    "mchawk": "McHawk",
    "mchowl": "McHowl",
    "mcknucks": "McKnucks",
    "mcmooch": "McMooch",
    "mcowl": "McOwl",
    "mcquirt": "McQuirt",
    "mcsixgun": "McSixgun",
    "mcswine": "McSwine",
    "mcterrier": "McTerrier",
    "mcviper": "McViper",
    "mcyard": "McYard",
    "mcsue": "McSue",
    "p.j.": "P.J. McBrine",
    "pago": "Pago Pago",
    "pango": "Pango Pango",
    "phoebus": "Phoebus Philea",
    "philea": "Phoebus Philea",
    "conippus": "Pippus Conippus",
    "pippus": "Pippus Conippus",
    "marco": "Marco Polo",
    "polo": "Marco Polo",
    "orb": "Orville Orb",
    "orville": "Orville Orb",
    "qualmy": "Qualmy Vista",
    "pulpheart": "Pulpheart Clabberhead",
    "rain-in-teepee": "Rain-in-Teepee",
    "rogers": "Autry Mack Brown Rogers",
    "rolls-smackhard": "Rolls-Smackhard",
    "scroogeville-on-the-latex": "Scroogeville-on-the-Latex",
    "s.mcd.": "S.McD.",
    "squeezem": "Squeezem, Fleecem, Skinem, and Skip",
    "swansdown-swoonsudden": "Swansdown-Swoonsudden",
    "swelldorf-castoria": "Swelldorf-Castoria",
    "tangkor": "Tangkor Wat",
    "wat": "Tangkor Wat",
    "triple-x": "Triple-X",
    "tryle": "Tryle N. Error",
    "wagga": "Wagga Wagga",
    "waha-go-gaga": "Waha-Go-Gaga",
}

# noinspection SpellCheckingInspection
ALL_CAPS = {
    "6-a-77",
    "b.b.",
    "b.p.f.b.",
    "ddt",
    "h.m.s.",
    "k-12",
    "k.o.",
    "l.a.",
    "l.t.a.b.",
    "s.a.",
    "s.o.s",
    "s.o.s.",
    "s.s",
    "s.w.",
    "t.n.t.",
    "u-2",
    "x-2",
    "xk-2",
}

# noinspection SpellCheckingInspection
BARKSIAN_NAMES: set[str] = {
    "abie",
    "abie's",
    "adam",
    "adam's",
    "admiral",
    "admirals",
    "aeetes's",
    "agavik",
    "agnes",
    "alexander",
    "ali",
    "alice",
    "alphonse",
    "amun",
    "angelboy",
    "angelface",
    "angina",
    "annie",
    "annie's",
    "aquapodicus",
    "arabic",
    "ares",
    "argo",
    "argo's",
    "argosy",
    "argus",
    "ariadne",
    "arky",
    "artefact",
    "astorbilt",
    "astorbilt's",
    "astorbilts",
    "atlas",
    "autry",
    "aztec",
    "azure",
    "azure's",
    "b",
    "b-36",
    "backdore",
    "balonio",
    "banzoony",
    "bara",
    "barkers",
    "barks",
    "barnaby",
    "barnowl",
    "barrymore",
    "bassofoglio",
    "batavia",
    "beakoff",
    "bedouin",
    "bedouins",
    "beelzebub",
    "ben",
    "bernard",
    "bernards",
    "bess",
    "bessie",
    "betlah",
    "betsy",
    "biceppa",
    "biglook",
    "birdmind",
    "blabaway",
    "blackheart",
    "blackie",
    "blacksnake",
    "blacksnake's",
    "blitzen",
    "blowsoutski",
    "bobbie",
    "bolivar",
    "bombastro",
    "bombie",
    "bombie's",
    "boone",
    "booneheads",
    "boreas",
    "bornworthy",
    "bosco",
    "bosco's",
    "brad",
    "bradley",
    "brahms",
    "brainwhiz",
    "brasshorn",
    "bratley",
    "bridie",
    "brigidita",
    "bruto",
    "bruto's",
    "buenaventura",
    "buffo",
    "bugmont",
    "bumblehead",
    "bumblehead's",
    "bummin'ham",
    "bumrisk",
    "caesar",
    "caledonian",
    "cantaloupa",
    "capitol",
    "carson",
    "casaba",
    "casey",
    "castoria",
    "charlemagne",
    "charlie",
    "chatterbeak",
    "christmas",
    "christmastime",
    "christmasy",
    "clabberhead",
    "clarabelle",
    "claus",
    "claus's",
    "clerkmore",
    "clipski",
    "columbus",
    "comanche",
    "confucius",
    "constanza",
    "corona",
    "cortez",
    "crabifolius",
    "craig",
    "creole",
    "croesus",
    "crusoe",
    "crustaceous",
    "cupid",
    "cuthbert",
    "cyril",
    "czar's",
    "dagga",
    "daisy",
    "daltons",
    "daly",
    "daniel",
    "dante",
    "davey",
    "dawson",
    "dean",
    "december",
    "delilah",
    "delore",
    "deltoid",
    "dervish",
    "dew-eee",
    "dew-eeeeee",
    "dewey",
    "dewey's",
    "diana",
    "dick",
    "dickens",
    "diego",
    "disney",
    "disney's",
    "disneyland",
    "dogdale",
    "donald",
    "donaldo",
    "donner",
    "donny",
    "dorotea",
    "duck",
    "ducko",
    "edgars",
    "edgerton",
    "edison",
    "egbert",
    "eiprah",
    "eisseb",
    "elena",
    "ellic",
    "eski",
    "eskimo",
    "eskimos",
    "esmeralda",
    "ezry",
    "fernando",
    "felina's",
    "fizzlebudget",
    "fleecem",
    "flintheart",
    "flinthide",
    "flinty",
    "flinty's",
    "flouncy",
    "flo",
    "franchy",
    "francis",
    "francisco",
    "francois",
    "frankenstein",
    "franklin",
    "fri",
    "froster",
    "fulldrip",
    "fulton",
    "galahad",
    "gar",
    "gaspar",
    "gaspar's",
    "gaston",
    "gearloose",
    "gearloose's",
    "genghis",
    "george",
    "gilfinkle",
    "giltwallets",
    "giltwhiskers",
    "gimleteye",
    "gladdy",
    "gladstone",
    "gladstone's",
    "glomgold",
    "gluck",
    "gluck's",
    "gnapoleon",
    "gnatbugg-mothley",
    "gnossy",
    "gnostradamus",
    "gobblechin",
    "goldbeak",
    "goldwad",
    "goofy",
    "goosehonk",
    "goosehonk's",
    "groanbalm",
    "gramps",
    "gus",
    "gyp",
    "gyro",
    "hamfat",
    "hamilton",
    "han",
    "harry",
    "heezoutski",
    "henry",
    "heston",
    "hiawatha",
    "hogby",
    "hogg",
    "hoppity",
    "horace",
    "huey",
    "i'm",
    "iglook",
    "ignacio",
    "ike's",
    "ila",
    "inez",
    "ironsides",
    "jackie",
    "james",
    "jan",
    "jane",
    "jason",
    "jeebs",
    "jesus",
    "jim",
    "jiminy",
    "jinglepurse",
    "jinglepurse's",
    "jingo",
    "jocko",
    "joe",
    "joes",
    "joey",
    "john",
    "jonah",
    "jones",
    "jonesie",
    "jonesy",
    "jorge",
    "jose",
    "josh",
    "josie",
    "juan",
    "juanita",
    "kakimaw",
    "kakimaws'",
    "khan",
    "laguna",
    "lancelot",
    "lardo",
    "larsen's",
    "lazy-k",
    "leary's",
    "leo",
    "limpspire",
    "linc",
    "lincoln",
    "lincolns",
    "longfellow's",
    "louie",
    "luis",
    "lulu",
    "ma\u00f1ana",
    "mack",
    "maggie",
    "magica",
    "mallard",
    "manana",
    "manco",
    "manuel",
    "marconi",
    "margarita",
    "maria",
    "mariah",
    "marmaduke",
    "matilda's",
    "mattressface",
    "mesmer",
    "miguel",
    "mike",
    "missilebug",
    "mon",
    "mona",
    "morgan",
    "morgan's",
    "morganbilt",
    "mozo",
    "mudhen",
    "mudhen's",
    "murphy",
    "murphy's",
    "murphys",
    "mustang",
    "mustapha",
    "nacy's",
    "nellie",
    "nevvawaza",
    "newrich",
    "northdale",
    "numa",
    "ole's",
    "oliver",
    "pablo",
    "paganini",
    "panchita",
    "panchita's",
    "pashly",
    "pattie",
    "pattie's",
    "patty",
    "pedro",
    "peeweegah",
    "peeweegahland",
    "peeweegahs",
    "peeweegahs'",
    "pendleton",
    "perry",
    "petrolio",
    "petruccio",
    "philo",
    "pierre",
    "pinjab",
    "pintail",
    "pizarro's",
    "plushcake",
    "poochley",
    "poochley's",
    "porkmuscle",
    "profundo",
    "pulpbugle",
    "pulpheart",
    "petunius",
    "putzoutski",
    "pyster",
    "quackenfuzz",
    "quackers",
    "quacko",
    "quagmire",
    "quahog",
    "queen",
    "quixote",
    "qwik",
    "raleigh",
    "raleigh's",
    "ramjckwckwizc",
    "ramona",
    "reggie",
    "remington",
    "rimfire",
    "ritzmore",
    "robert",
    "robinson",
    "rockdust",
    "rockjaw",
    "rockstone",
    "rodin",
    "rodney",
    "roger",
    "rolando",
    "rolando's",
    "roscoe's",
    "ryan",
    "sagmore",
    "sagmore's",
    "sairy",
    "sammy",
    "santa",
    "scarpuss",
    "schubert",
    "scotch",
    "scott",
    "scottie",
    "scottie's",
    "scrooge",
    "scrooge's",
    "scroogie",
    "senga",
    "september",
    "sepulveda",
    "sevenchins",
    "sheba",
    "shoeless",
    "si",
    "sidney",
    "simon",
    "skinem",
    "smoogle-snaghles",
    "smorgie",
    "snoggin",
    "snoggin's",
    "snootley",
    "snootley's",
    "snootsbury",
    "snozzie",
    "socrapossi's",
    "solomon",
    "solomon's",
    "spellcaster",
    "spinderella",
    "squanderbilt",
    "squattie",
    "squattie's",
    "squatty",
    "stickaree",
    "stickarees",
    "stumpalong",
    "swamphole",
    "swamphole's",
    "swelldorf",
    "swoonsudden",
    "sylvester",
    "tagalong",
    "teengiggle",
    "teresa",
    "theodore",
    "theseus",
    "thinknoble",
    "thor",
    "throckmorton",
    "thur",
    "thunderface",
    "tina",
    "tiva",
    "tombsbury",
    "trestleman",
    "truckhorse",
    "trueshot",
    "tue",
    "tuku",
    "tupec",
    "tweeksdale",
    "tuesday",
    "tuesdays",
    "tyrannosaurus",
    "unca",
    "unca'",
    "umble",
    "umble's",
    "unkie",
    "utterbunk",
    "vaquero",
    "vaselino",
    "vaudeville",
    "verdugo",
    "veronica",
    "victoria's",
    "victorian",
    "vishnu",
    "walt",
    "walter",
    "washingtons",
    "watt",
    "whirlman",
    "winnie",
    "wisie",
    "wormsley",
    "yelly",
    "yonson",
    "yonson's",
    "zippo",
}

# noinspection SpellCheckingInspection
BARKSIAN_PLACE_RELATED_WORDS: set[str] = {
    "abilene",
    "acapulco",
    "africa",
    "african",
    "alabammy",
    "alaskan",
    "america",
    "america's",
    "american",
    "americano",
    "americanos",
    "americans",
    "amazon",
    "andes",
    "andean",
    "antarctic",
    "antarctica",
    "antofagasta",
    "arab",
    "arabian",
    "arctic",
    "arnhem",
    "artichokus",
    "asia",
    "assyrian",
    "atlantic",
    "atlantis",
    "awfultonians",
    "australian",
    "babylon",
    "bagdad",
    "baloni",
    "balonia",
    "balonian",
    "barcelona",
    "bechuanaland",
    "belgian",
    "bengali",
    "bermuda",
    "betelgeuse",
    "blackjack's",
    "bluebeard's",
    "bolonian",
    "borneo",
    "boston",
    "botofoga",
    "brazilian",
    "brisbane",
    "british",
    "brooklyn",
    "brutopia",
    "brutopia's",
    "brutopian",
    "brutopians",
    "bulgarian",
    "bumpanian",
    "bumpanians",
    "bumpay",
    "burbank",
    "burgeria",
    "burma",
    "cairo",
    "calcutta",
    "caledonia",
    "calisota",
    "capetown",
    "capri",
    "caribbean",
    "carlsbad",
    "carolina",
    "carthage",
    "casablanca",
    "catalina",
    "cathay",
    "chaldee",
    "chicago",
    "chilcoot",
    "chiliburgeria",
    "chillifoot",
    "chinaman",
    "chinese",
    "cibola",
    "cibolans",
    "colchis",
    "corvallis",
    "crete",
    "cretan",
    "curacao",
    "cuzco",
    "damascus",
    "danube",
    "dayton",
    "denver",
    "dixie",
    "dixieland",
    "dizzydrop",
    "duckburg",
    "duckburg's",
    "duckburgian",
    "dutchman's",
    "egyptian",
    "england",
    "english",
    "europe",
    "faka",
    "fakfak",
    "floodout",
    "french",
    "frozenbear",
    "ghaspan",
    "ghulp",
    "glasgow",
    "glendale",
    "gooseberry",
    "granada",
    "greenland",
    "guinea",
    "hackensack",
    "hindu",
    "hollywood",
    "hottentot",
    "howduyustan",
    "ironheelia",
    "india",
    "itsa",
    "jac",
    "jacinto",
    "jugneck",
    "jupiter",
    "kankakee",
    "kashmir",
    "klondike",
    "kokomo",
    "kush",
    "lapland",
    "limpopo",
    "london",
    "marseille",
    "mayan",
    "mexican",
    "mongolian",
    "mongoosia",
    "monterey",
    "mushmore",
    "newfoundland",
    "orion",
    "orkney",
    "pacific",
    "palo",
    "persia",
    "philadelphia",
    "phonus",
    "pickleburg",
    "pittsboig",
    "pocatelly",
    "podunk",
    "potomac",
    "pumpkinburg",
    "quackville",
    "riviera",
    "rockies",
    "sacramento",
    "san",
    "scotland",
    "scroogeville",
    "seville",
    "siam",
    "siamese",
    "sinai",
    "skeetertown",
    "sourweather",
    "spanish",
    "swanville",
    "swingingdore",
    "sulu",
    "sydney",
    "tasmainia",
    "thrushwhistle",
    "thule",
    "timbuctoo",
    "tokyo",
    "trinidad",
    "tripoli",
    "tropicania",
    "tropics",
    "tulebug",
    "tuleburg",
    "tuleville",
    "turkish",
    "valencia",
    "venus",
    "venusian",
    "verbena",
    "vesuvius",
    "vine",
    "virginny",
    "volcanovia",
    "volcanovian",
    "volga",
    "whambesi",
    "yucatan",
    "zanzibar",
    "zululand",
}

COUNTRIES: set[str] = {
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "antigua & deps",
    "argentina",
    "armenia",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bhutan",
    "bolivia",
    "bosnia herzegovina",
    "botswana",
    "brazil",
    "britain",
    "brunei",
    "bulgaria",
    "burkina",
    "burma",
    "burundi",
    "cambodia",
    "cameroon",
    "canada",
    "cape verde",
    "central african rep",
    "chad",
    "chile",
    "china",
    "columbia",
    "comoros",
    "congo",
    "congo {democratic rep}",
    "costa rica",
    "croatia",
    "cuba",
    "cyprus",
    "czech republic",
    "denmark",
    "djibouti",
    "dominica",
    "dominican republic",
    "east timor",
    "ecuador",
    "egypt",
    "el salvador",
    "equatorial guinea",
    "eritrea",
    "estonia",
    "ethiopia",
    "fiji",
    "finland",
    "france",
    "gabon",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "greece",
    "grenada",
    "guatemala",
    "guinea",
    "guinea-bissau",
    "guyana",
    "haiti",
    "honduras",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "israel",
    "italy",
    "ivory coast",
    "jamaica",
    "japan",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "korea north",
    "korea south",
    "kosovo",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "macedonia",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "marshall islands",
    "mauritania",
    "mauritius",
    "mexico",
    "micronesia",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "morocco",
    "mozambique",
    "myanmar",
    "namibia",
    "nauru",
    "nepal",
    "netherlands",
    "new zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "norway",
    "oman",
    "pakistan",
    "palau",
    "panama",
    "papua new guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "qatar",
    "romania",
    "russian federation",
    "rwanda",
    "st kitts & nevis",
    "st lucia",
    "saint vincent & the grenadines",
    "samoa",
    "san marino",
    "sao tome & principe",
    "saudi arabia",
    "senegal",
    "serbia",
    "seychelles",
    "sierra leone",
    "singapore",
    "slovakia",
    "slovenia",
    "solomon islands",
    "somalia",
    "south africa",
    "south sudan",
    "spain",
    "sri lanka",
    "sudan",
    "suriname",
    "swaziland",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "togo",
    "tonga",
    "trinidad & tobago",
    "tunisia",
    # "turkey",
    "turkmenistan",
    "tuvalu",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "united states",
    "uruguay",
    "uzbekistan",
    "vanuatu",
    "vatican city",
    "venezuela",
    "vietnam",
    "yemen",
    "zambia",
    "zimbabwe",
}

BARKSIAN_WORDS_WITH_OPTIONAL_HYPHENS: set[str] = {
    "13-13",
    "a-ha",
    "ba-woom",
    "bee-yootiful",
    "boo-hoo",
    "bull-headed",
    "c-o-w-b-o-y",
    "coo-coo",
    "dead-beat",
    "dead-beats",
    "ee-yah",
    "f-i-f-t-y",
    "good-by",
    "good-bye",
    "hi-de-ho",
    "hi-jacked",
    "hm-m-m",
    "hook-up",
    "horse-radish",
    "i-i",
    "i-n-n",
    "j-u-k-e-b-o-x",
    "kind-hearted",
    "life-saving",
    "like-um",
    "low-down",
    "m-mm",
    "make-um",
    "n-i-c-k-e-l",
    "near-by",
    "nitro-glycerine",
    "o-oh",
    "o-u-2",
    "ou-2",
    "out-smarting",
    "p-l-a-y",
    "p-u-t",
    "r-a-t",
    "r-r-r",
    "r-r-r-r",
    "radar-scope",
    "round-up",
    "s-c-r-e-a-m-i-n-g",
    "set-up",
    "sight-seeing",
    "single-handed",
    "six-guns",
    "sky-high",
    "so-so",
    "spy-glass",
    "ta-ta",
    "tin-horn",
    "woo-oo",
    "y-a-k's",
    "ya-woo",
    "yi-yi",
    "yo'-all",
}

BARKSIAN_EXTRA_TERMS = BARKSIAN_FULL_NAMES.union(
    BARKSIAN_PLACES_FULL_NAMES.union(BARKSIAN_THINGS_FULL_NAMES).union(
        BARKSIAN_TITLES.union(BARKSIAN_MISC_FULL_NAMES)
    )
)

TERMS_TO_CAPITALIZE: set[str] = (
    BARKSIAN_NAMES.union(BARKSIAN_PLACE_RELATED_WORDS).union(US_STATES).union(COUNTRIES)
)
