from barks_fantagraphics.barks_words import US_STATES

TERMS_TO_REMOVE: set[str] = {
    "_",
}

# noinspection SpellCheckingInspection
BARKSIAN_FULL_NAMES: set[str] = {
    "Benzine Banzoony",
    "B.P.F.B.",
    "Chisel McSue",
    "Daredevil Daly",
    "Diamond Dick",
    "Don Gaspar",
    "Don Porko de Lardo",
    "Porko de Lardo",
    "Dr. U. Qwik",
    "Finnan Haddie",
    "Francisco de Ulloa",
    "Heston Froster",
    "Horseshoe Hogg",
    "Jim Dandy",
    "John the Junkman",
    "Jughead Jones's",
    "Manana N. de Patio",
    "Olaf the Blue",
    "Philo T. Ellic",
    "Prof. Batty",
    "Queen of the Kangaroos",
    "Queen of Seiprah",
    "Queen Bess",
    "Queen Mary",
    "Queen Veronica",
    "Queen Victoria's",
    "Ramrod Ransom",
    "Rodney McHowl",
    "Smoked Barracuda",
    "Trigger Trueshot",
    "Unca' Donald",
    "Uncle Donald",
    "Unca' Scrooge",
    "Uncle Scrooge",
    "Wild Bill Carson",
}

# noinspection SpellCheckingInspection
BARKSIAN_PLACES_FULL_NAMES: set[str] = {
    "Ancient Cathay",
    "Ancient Egyptian",
    "Barnacle Bay",
    "Beaver Tail Lake",
    "Brown Derby",
    "Codfish Cove",
    "Columbia River",
    "Cornpone Gables",
    "Darkest Africa",
    "Dayton Street",
    "El Dorado",
    "Gneezle Gnob",
    "Hag's Fang Cliff",
    "Lower California",
    "North America",
    "San Antone",
    "San Diego",
    "San Joaquin Valley",
    "Snarling Rocks Bay",
    "Sutter's Fort",
    "Thrushwistle Glen",
    "Upper Whambesi",
}

# noinspection SpellCheckingInspection
BARKSIAN_THINGS_FULL_NAMES: set[str] = {
    "Belgian Prince Leopold",
    "Bungling Bros Circus",
    "Casa del Hoosier Motel",
    "cat-o'-nine-tails",
    "Cotton Queen",
    "Eager Edgars",
    "Lobster NewbUrg",
    "Quackly Hall",
    "Ramona Pageant Bowl",
    "River Belle",
    "Squanderbilt Hotel",
    "Worry Room",
}

# TODO: Maybe put these in map?
# noinspection SpellCheckingInspection
BARKSIAN_TITLES: set[str] = {
    "Blistering Bullets",
    "Bullet Pizen At Rustlers' Gallows",
    "Carnage on the Cimarron",
    "Fagin's Fangs",
    "Ghost of the Gunnison",
    "Gore in the Gully",
    "Gory Gap",
    "Gunsmoke Gulch",
    "Gunfire on the Rio",
    "Law of the Roaring Winchesters",
    "Powderburns on the Powderhorn",
    "Sagebrush Savage",
    "Wonderhead Son of Ticka",
}

# noinspection SpellCheckingInspection
BARKSIAN_MISC_FULL_NAMES: set[str] = {
    "Blue Danube",
    "Blue Danube Waltz",
    "Brahms Concerto",
}

# noinspection SpellCheckingInspection
BARKSIAN_NAMES: set[str] = {
    "abie",
    "abie's",
    "adam",
    "adam's",
    "admiral",
    "admirals",
    "aeetes's",
    "agavik",
    "agnes",
    "alexander",
    "ali",
    "angina",
    "aquapodicus",
    "arabic",
    "ares",
    "argo",
    "argo's",
    "argosy",
    "argus",
    "ariadne",
    "arky",
    "artefact",
    "astorbilt",
    "atlas",
    "autry",
    "aztec",
    "azure",
    "b",
    "B-36",
    "b.b.",
    "backdore",
    "balonio",
    "banzoony",
    "bara",
    "barks",
    "barnaby",
    "barnowl",
    "barrymore",
    "bassofoglio",
    "batavia",
    "beakoff",
    "beelzebub",
    "bernard",
    "bernards",
    "bess",
    "bessie",
    "betlah",
    "betsy",
    "biceppa",
    "biglook",
    "blacksnake",
    "blacksnake's",
    "blitzen",
    "blowsoutski",
    "bobbie",
    "bolivar",
    "bombastro",
    "bombie",
    "bombie's",
    "boone",
    "booneheads",
    "boreas",
    "bornworthy",
    "bosco",
    "bosco's",
    "brad",
    "brahms",
    "bratley",
    "brigidita",
    "bruto",
    "bruto's",
    "buenaventura",
    "bugmont",
    "bumblehead",
    "bumblehead's",
    "bummin'ham",
    "bumrisk",
    "caesar",
    "caledonian",
    "cantaloupa",
    "capitol",
    "carson",
    "casaba",
    "casey",
    "castoria",
    "charlemagne",
    "charlie",
    "chatterbeak",
    "christmas",
    "christmastime",
    "clabberhead",
    "clarabelle",
    "claus",
    "clipski",
    "columbus",
    "comanche",
    "constanza",
    "cortez",
    "crabifolius",
    "craig",
    "creole",
    "crustaceous",
    "cuthbert",
    "cyril",
    "daisy",
    "daltons",
    "daly",
    "daniel",
    "dante",
    "davey",
    "dawson",
    "dean",
    "delilah",
    "deltoid",
    "dewey",
    "diana",
    "dick",
    "dickens",
    "diego",
    "donald",
    "donaldo",
    "donner",
    "donny",
    "dorotea",
    "duck",
    "ducko",
    "edgars",
    "edgerton",
    "edison",
    "egbert",
    "eiprah",
    "eisseb",
    "elena",
    "ellic",
    "eski",
    "eskimo",
    "eskimos",
    "esmeralda",
    "ezry",
    "fernando",
    "fizzlebudget",
    "fleecem",
    "flinthide",
    "froster",
    "gaspar",
    "gaston",
    "gearloose",
    "gilfinkle",
    "giltwhiskers",
    "gimleteye",
    "gladstone",
    "glomgold",
    "gnapoleon",
    "gnatbugg-mothley",
    "gnossy",
    "gnostradamus",
    "gobblechin",
    "goldbeak",
    "goofy",
    "groanbalm",
    "gyp",
    "gyro",
    "hamilton",
    "harry",
    "heezoutski",
    "heston",
    "hogg",
    "hoppity",
    "horace",
    "huey",
    "i'm",
    "iglook",
    "ignacio",
    "ila",
    "jackie",
    "jason",
    "jeebs",
    "jesus",
    "jim",
    "jiminy",
    "jingo",
    "joe",
    "joes",
    "joey",
    "john",
    "jonah",
    "jones",
    "jonesie",
    "jonesy",
    "jorge",
    "jose",
    "josh",
    "josie",
    "juan",
    "juanita",
    "lazy-k",
    "louie",
    "luis",
    "ma\u00f1ana",
    "mack",
    "magica",
    "mallard",
    "manana",
    "manco",
    "manuel",
    "marconi",
    "margarita",
    "maria",
    "marmaduke",
    "mattressface",
    "miguel",
    "mike",
    "morganbilt",
    "mustang",
    "mustapha",
    "nacy's",
    "nevvawaza",
    "pablo",
    "paganini",
    "panchita",
    "panchita's",
    "pattie",
    "pattie's",
    "pedro",
    "petrolio",
    "petruccio",
    "philo",
    "poochley",
    "poochley's",
    "pulpheart",
    "putzoutski",
    "quacko",
    "quagmire",
    "queen",
    "qwik",
    "raleigh",
    "raleigh's",
    "ramjckwckwizc",
    "ramona",
    "remington",
    "rimfire",
    "rodney",
    "rolando",
    "rolando's",
    "sairy",
    "santa",
    "scarpuss",
    "scrooge",
    "senga",
    "sepulveda",
    "sevenchins",
    "si",
    "skinem",
    "smoogle-snaghles",
    "smorgie",
    "snootsbury",
    "socrapossi's",
    "squanderbilt",
    "squattie",
    "squattie's",
    "stumpalong",
    "swamphole",
    "swamphole's",
    "swelldorf",
    "sylvester",
    "tagalong",
    "theodore",
    "throckmorton",
    "tina",
    "tombsbury",
    "trueshot",
    "tupec",
    "tweeksdale",
    "tuesday",
    "vaquero",
    "vaselino",
    "vaudeville",
    "verdugo",
    "veronica",
    "walter",
    "wormsley",
}

# noinspection SpellCheckingInspection
NAME_MAP: dict[str, str] = {
    "almostus": "Almostus Extinctus",
    "extinctus": "Almostus Extinctus",
    "extinctuses": "Almostus Extinctuses",
    "angeles": "Los Angeles",
    "los": "Los Angeles",
    "antone": "San Antone",
    "b-197": "B-197 X-NG",
    "x-ng": "B-197 X-NG",
    "b-boys": "B-Boys",
    "b-boys'": "B-Boys'",
    "boer": "Boer War",
    "casaba": "Casaba Cantaloupa",
    "chillspine": "Chillspine Buoy",
    "codfeesh": "Codfeesh Cove",
    "coney": "Coney Island",
    "costa": "Costa Rica",
    "creole": "Creole Belle",
    "daniel": "Daniel Boone",
    "ddt": "DDT",
    "debbies": "Junior Sub-teen-age Debbies Club",
    "dick": "Diamond Dick",
    "donna": "Donna Duck",
    "frozenbear": "Frozenbear Lake",
    "hagtooth": "Hagtooth Rock",
    "l.t.a.b.": "L.T.A.B.",
    "lazy-k": "Lazy-K",
    "mc-who": "Mc-Who",
    "mammalarius": "Mammalarius Aquapodicus",
    "mcarchives": "McArchives",
    "mcchicken": "McChicken",
    "mccobb": "McCobb",
    "mccornburger's": "McCornburger's",
    "mccoy": "McCoy",
    "mccrow": "McCrow",
    "mcdome": "McDome",
    "mcduck": "McDuck",
    "mcduck's": "McDuck's",
    "mcducks": "McDucks",
    "mceagle": "McEagle",
    "mceye": "McEye",
    "mcfiendy": "McFiendy",
    "mcgillicuddy": "McGillicuddy",
    "mchawk": "McHawk",
    "mchowl": "McHowl",
    "mcknucks": "McKnucks",
    "mcmooch": "McMooch",
    "mcowl": "McOwl",
    "mcquirt": "McQuirt",
    "mcsixgun": "McSixgun",
    "mcterrier": "McTerrier",
    "mcviper": "McViper",
    "mcyard": "McYard",
    "mcsue": "McSue",
    "phoebus": "Phoebus Philea",
    "philea": "Phoebus Philea",
    "conippus": "Pippus Conippus",
    "pippus": "Pippus Conippus",
    "marco": "Marco Polo",
    "polo": "Marco Polo",
    "orb": "Orville Orb",
    "orville": "Orville Orb",
    "pulpheart": "Pulpheart Clabberhead",
    "rogers": "Autry Mack Brown Rogers",
    "scroogeville-on-the-latex": "Scroogeville-on-the-Latex",
    "squeezem": "Squeezem, Fleecem, Skinem, and Skip",
    "swansdown-swoonsudden": "Swansdown-Swoonsudden",
    "swelldorf-castoria": "Swelldorf-Castoria",
    "t.n.t.": "T.N.T.",
    "triple-x": "Triple-X",
    "tryle": "Tryle N. Error",
    "waha-go-gaga": "Waha-Go-Gaga",
}

# noinspection SpellCheckingInspection
BARKSIAN_PLACE_RELATED_WORDS: set[str] = {
    "abilene",
    "acapulco",
    "africa",
    "african",
    "alaskan",
    "america",
    "america's",
    "american",
    "americano",
    "americanos",
    "americans",
    "andes",
    "andean",
    "antarctica",
    "arctic",
    "asia",
    "assyrian",
    "atlantic",
    "atlantis",
    "awfultonians",
    "babylon",
    "bagdad",
    "balonia",
    "balonian",
    "barcelona",
    "belgian",
    "bermuda",
    "blackjack's",
    "bluebeard's",
    "bolonian",
    "borneo",
    "boston",
    "brazilian",
    "british",
    "brooklyn",
    "bumpanian",
    "bumpanians",
    "bumpay",
    "burbank",
    "burgeria",
    "burma",
    "calcutta",
    "calisota",
    "capetown",
    "carthage",
    "casablanca",
    "catalina",
    "cathay",
    "chaldee",
    "chicago",
    "chilcoot",
    "chiliburgeria",
    "chinese",
    "cibola",
    "cibolans",
    "colchis",
    "crete",
    "cretan",
    "cuzco",
    "damascus",
    "danube",
    "dayton",
    "dixie",
    "dixieland",
    "duckburg",
    "egyptian",
    "england",
    "english",
    "europe",
    "floodout",
    "frozenbear",
    "granada",
    "greenland",
    "hollywood",
    "howduyustan",
    "ironheelia",
    "jupiter",
    "klondike",
    "marseille",
    "mayan",
    "monterey",
    "newfoundland",
    "pacific",
    "persia",
    "pickleburg",
    "pumpkinburg",
    "quackville",
    "sacramento",
    "scotland",
    "scroogeville",
    "seville",
    "spanish",
    "swingingdore",
    "sydney",
    "timbuctoo",
    "tokyo",
    "tripoli",
    "tropicania",
    "tropics",
    "valencia",
    "venus",
    "verbena",
    "vine",
    "volcanovia",
    "volcanovian",
    "whambesi",
}

COUNTRIES: set[str] = {
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "antigua & deps",
    "argentina",
    "armenia",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bhutan",
    "bolivia",
    "bosnia herzegovina",
    "botswana",
    "brazil",
    "brunei",
    "bulgaria",
    "burkina",
    "burma",
    "burundi",
    "cambodia",
    "cameroon",
    "canada",
    "cape verde",
    "central african rep",
    "chad",
    "chile",
    "china",
    "colombia",
    "comoros",
    "congo",
    "congo {democratic rep}",
    "costa rica",
    "croatia",
    "cuba",
    "cyprus",
    "czech republic",
    "denmark",
    "djibouti",
    "dominica",
    "dominican republic",
    "east timor",
    "ecuador",
    "egypt",
    "el salvador",
    "equatorial guinea",
    "eritrea",
    "estonia",
    "ethiopia",
    "fiji",
    "finland",
    "france",
    "gabon",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "greece",
    "grenada",
    "guatemala",
    "guinea",
    "guinea-bissau",
    "guyana",
    "haiti",
    "honduras",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "israel",
    "italy",
    "ivory coast",
    "jamaica",
    "japan",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "korea north",
    "korea south",
    "kosovo",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "macedonia",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "marshall islands",
    "mauritania",
    "mauritius",
    "mexico",
    "micronesia",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "morocco",
    "mozambique",
    "myanmar",
    "namibia",
    "nauru",
    "nepal",
    "netherlands",
    "new zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "norway",
    "oman",
    "pakistan",
    "palau",
    "panama",
    "papua new guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "qatar",
    "romania",
    "russian federation",
    "rwanda",
    "st kitts & nevis",
    "st lucia",
    "saint vincent & the grenadines",
    "samoa",
    "san marino",
    "sao tome & principe",
    "saudi arabia",
    "senegal",
    "serbia",
    "seychelles",
    "sierra leone",
    "singapore",
    "slovakia",
    "slovenia",
    "solomon islands",
    "somalia",
    "south africa",
    "south sudan",
    "spain",
    "sri lanka",
    "sudan",
    "suriname",
    "swaziland",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "togo",
    "tonga",
    "trinidad & tobago",
    "tunisia",
    # "turkey",
    "turkmenistan",
    "tuvalu",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "united states",
    "uruguay",
    "uzbekistan",
    "vanuatu",
    "vatican city",
    "venezuela",
    "vietnam",
    "yemen",
    "zambia",
    "zimbabwe",
}

BARKSIAN_EXTRA_TERMS = BARKSIAN_FULL_NAMES.union(
    BARKSIAN_PLACES_FULL_NAMES.union(BARKSIAN_THINGS_FULL_NAMES).union(
        BARKSIAN_TITLES.union(BARKSIAN_MISC_FULL_NAMES)
    )
)

TERMS_TO_CAPITALIZE: set[str] = (
    BARKSIAN_NAMES.union(BARKSIAN_PLACE_RELATED_WORDS).union(US_STATES).union(COUNTRIES)
)
