"""Refresh ``cpi_table.py``, the yearly CPI figures, from the U.S. BLS.

The inflation calculator (:func:`comic_utils.cpi_calculator.get_adjusted_usd`)
needs one number a year: the CPI-U for all items in the U.S. city average, all
urban consumers (series ``CUUR0000SA0``). This downloads the BLS "All Items" flat
file, keeps that series, averages each year's published values (the months, and
the annual average where BLS gives one), and rewrites ``cpi_table.py`` with them.

The BLS publishes a new month's figure monthly; run this now and then::

    python -m comic_utils.update_cpi_table

It refuses a download whose latest year is older than the table's, and writes the
new table only once the whole download has been read.
"""

from __future__ import annotations

import argparse
import ast
import sys
import urllib.error
import urllib.request
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

TABLE_PATH = Path(__file__).parent / "cpi_table.py"
SERIES_ID = "CUUR0000SA0"

# BLS bulk flat file holding every CPI-U "All Items" (item SA0) series, back to 1913.
BLS_ALL_ITEMS_URL = "https://download.bls.gov/pub/time.series/cu/cu.data.1.AllItems"
# BLS returns HTTP 403 to requests whose User-Agent is missing or looks like a
# library/bot default. A descriptive User-Agent with a contact email is required.
DEFAULT_USER_AGENT = "BarksReader-cpi-updater/1.0 (gregg.kay@gmail.com)"
DOWNLOAD_TIMEOUT_SECONDS = 120

_HEADER = '''\
"""The CPI figures the inflation calculator uses: one per year.

Generated by ``python -m comic_utils.update_cpi_table``; do not edit by hand. The
U.S. BLS CPI-U, all items in the U.S. city average, all urban consumers (series
{series}): each year's average of its published values (the months, and the annual
average where BLS gives one). The latest year is partial until its December figure
is out.
"""

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

SERIES_ID: Final = "{series}"

ANNUAL_CPI: Final[Mapping[int, float]] = MappingProxyType(
    {{
'''
_FOOTER = """\
    }
)
"""


@dataclass(frozen=True)
class UpdateResult:
    """What an update wrote: the table's years, and its latest before and after."""

    table_path: Path
    years: int
    previous_latest_year: int | None
    latest_year: int


def download_all_items(
    url: str = BLS_ALL_ITEMS_URL,
    user_agent: str = DEFAULT_USER_AGENT,
    timeout: int = DOWNLOAD_TIMEOUT_SECONDS,
) -> str:
    """Download the BLS 'All Items' flat file and return its text.

    Raises:
        urllib.error.HTTPError: If BLS rejects the request (e.g. 403).
        urllib.error.URLError: If the request otherwise fails (e.g. no network).

    """
    request = urllib.request.Request(url, headers={"User-Agent": user_agent})  # noqa: S310
    with urllib.request.urlopen(request, timeout=timeout) as response:  # noqa: S310
        return response.read().decode("utf-8")


def annual_averages(text: str, series_id: str = SERIES_ID) -> dict[int, float]:
    """Return each year's average of a series' values in BLS flat-file text.

    The format is tab-delimited with a header row; fields are padded with
    whitespace. Rows whose value is missing or not a number (suppressed
    observations) are skipped.
    """
    values: defaultdict[int, list[float]] = defaultdict(list)
    for line in text.splitlines()[1:]:  # the header row
        fields = line.split("\t")
        if len(fields) < 4 or fields[0].strip() != series_id:  # noqa: PLR2004 (series, year, period, value)
            continue
        try:
            year = int(fields[1].strip())
            value = float(fields[3].strip())
        except ValueError:
            continue
        values[year].append(value)
    return {year: sum(vals) / len(vals) for year, vals in sorted(values.items())}


def render_table(table: dict[int, float], series_id: str = SERIES_ID) -> str:
    """Return ``cpi_table.py``'s source for a year-to-CPI table, as ruff formats it."""
    rows = "".join(f"        {year}: {value!r},\n" for year, value in sorted(table.items()))
    return _HEADER.format(series=series_id) + rows + _FOOTER


def read_table(path: Path = TABLE_PATH) -> dict[int, float]:
    """Return the table in a ``cpi_table.py``, read as data (empty if there is none)."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    for node in ast.walk(tree):
        if isinstance(node, ast.Dict):
            return ast.literal_eval(node)
    return {}


def update_cpi_table(
    table_path: Path = TABLE_PATH,
    *,
    url: str = BLS_ALL_ITEMS_URL,
    user_agent: str = DEFAULT_USER_AGENT,
    timeout: int = DOWNLOAD_TIMEOUT_SECONDS,
) -> UpdateResult:
    """Rewrite ``cpi_table.py`` from the BLS.

    Raises:
        urllib.error.URLError: If the download fails.
        ValueError: If the download has no data for the series, or ends earlier
            than the table it would replace.

    """
    table = annual_averages(download_all_items(url, user_agent, timeout))
    if not table:
        msg = f"the BLS download has no data for series {SERIES_ID}"
        raise ValueError(msg)
    previous = read_table(table_path)
    previous_latest = max(previous) if previous else None
    latest = max(table)
    if previous_latest is not None and latest < previous_latest:
        msg = (
            f"refusing the update: the download ends {latest}, before the table's {previous_latest}"
        )
        raise ValueError(msg)
    staged = table_path.with_suffix(".py.new")
    staged.write_text(render_table(table), encoding="utf-8")
    staged.replace(table_path)
    return UpdateResult(table_path, len(table), previous_latest, latest)


def main(argv: list[str] | None = None) -> int:
    """Run the update from the command line; return the exit status."""
    parser = argparse.ArgumentParser(description="Refresh cpi_table.py from the BLS.")
    parser.add_argument("--table", type=Path, default=TABLE_PATH, help="the table to rewrite")
    args = parser.parse_args(argv)
    try:
        result = update_cpi_table(args.table)
    except (OSError, urllib.error.URLError, ValueError) as error:
        print(f"update_cpi_table: {error}", file=sys.stderr)  # noqa: T201
        return 1
    print(  # noqa: T201
        f"update_cpi_table: {result.years} years, to {result.latest_year}"
        f" (was {result.previous_latest_year}): {result.table_path}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
