"""Guard the pre-baked "All One-Pagers" collection pages in the FANTA_01 override.

The collection is served to the reader as ordinary "extra" pages of the FANTA_01
volume, numbered from ``ONE_PAGER_COLLECTION_PAGE_BASE`` (500) upward - one page
per *located* one-pager (``get_located_one_pagers``), in chronological order.
These pages are pre-baked (encrypted) into the FANTA_01 override archive and are
no longer regenerated by any script, so this test pins them down: the override
zip must contain *exactly* the contiguous collection pages ``500 .. 500+N-1``,
one entry each, where ``N`` is the number of located one-pagers.

The page extension is deliberately not pinned. The reader keys the override's
extras map by page *stem* and accepts either extension, and the archive already
mixes both (a page re-baked after a fix is stored losslessly as ``.png``), so
requiring ``.jpg`` would assert a convention neither the runtime nor the data
actually has. What must hold is that each page appears exactly once - a page
stored as both ``.jpg`` and ``.png`` is a real fault, and the reader raises on it.

Unlike the rest of the suite, this reads the real (machine-local) reader override
archive under ``FANTA_VOLUME_OVERRIDES_ROOT``. Locally a missing archive is a hard
failure (it guards against the baked pages drifting), but on CI - where this
machine-local data legitimately does not exist - the test is skipped instead.
"""

from __future__ import annotations

import os
import zipfile
from pathlib import Path

import pytest
from barks_fantagraphics.comic_book_info import (
    ONE_PAGER_COLLECTION_PAGE_BASE,
    ONE_PAGER_COLLECTION_VOLUME,
    get_located_one_pagers,
)
from barks_fantagraphics.comics_consts import FANTA_VOLUME_OVERRIDES_ROOT
from barks_fantagraphics.fanta_comics_info import FANTA_OVERRIDE_ZIPS

# The collection's nominal volume - its pages live as "extra" images here.
COLLECTION_VOLUME = ONE_PAGER_COLLECTION_VOLUME

COLLECTION_PAGE_EXTS = (".jpg", ".png")
# The stored image bytes are Fernet ciphertext, which always begins with this.
FERNET_TOKEN_PREFIX = b"gAAAA"


def _override_zip_path() -> Path:
    return FANTA_VOLUME_OVERRIDES_ROOT / FANTA_OVERRIDE_ZIPS[COLLECTION_VOLUME]


def _page_num(arcname: str) -> int | None:
    stem = Path(arcname).stem
    return int(stem) if stem.isdigit() else None


def _expected_collection_pages() -> list[int]:
    """Return the contiguous collection page numbers, one per located one-pager."""
    located = get_located_one_pagers()
    return [ONE_PAGER_COLLECTION_PAGE_BASE + i for i in range(len(located))]


@pytest.fixture(scope="module")
def override_zip_path() -> Path:
    """Path to the real FANTA_01 override archive.

    Hard-fails if absent locally; skips on CI, where the archive does not exist.
    """
    zip_path = _override_zip_path()
    if not zip_path.is_file():
        msg = f'FANTA_01 override archive is missing: "{zip_path}".'
        if os.environ.get("CI"):
            pytest.skip(msg)
        pytest.fail(msg)
    return zip_path


@pytest.fixture(scope="module")
def override_names(override_zip_path: Path) -> list[str]:
    """Entry names of the real FANTA_01 override archive."""
    with zipfile.ZipFile(override_zip_path, "r") as zf:
        return zf.namelist()


@pytest.fixture(scope="module")
def collection_names(override_names: list[str]) -> list[str]:
    """Override entries belonging to the one-pager collection (page >= base)."""
    return [
        name
        for name in override_names
        if (page := _page_num(name)) is not None and page >= ONE_PAGER_COLLECTION_PAGE_BASE
    ]


class TestOnePagerCollectionPages:
    def test_located_one_pagers_present(self) -> None:
        # The collection (and so this test) is meaningless with nothing to bake.
        assert get_located_one_pagers(), "No located one-pagers (ONE_PAGER_LOCATIONS all _TODO)."

    def test_collection_pages_match_located_one_pagers_exactly(
        self, collection_names: list[str]
    ) -> None:
        # Exactly the contiguous pages 500..500+N-1, whatever the extension: no missing
        # pages, no stale extras, and no page stored twice under two extensions.
        pages = sorted(page for name in collection_names if (page := _page_num(name)))
        assert pages == _expected_collection_pages()
        bad_ext = [n for n in collection_names if Path(n).suffix not in COLLECTION_PAGE_EXTS]
        assert not bad_ext, f"Collection pages with an unreadable extension: {bad_ext}."

    def test_collection_pages_are_nonempty_encrypted_images(
        self, override_zip_path: Path, collection_names: list[str]
    ) -> None:
        by_page = {page: name for name in collection_names if (page := _page_num(name))}
        with zipfile.ZipFile(override_zip_path, "r") as zf:
            for page in _expected_collection_pages():
                arcname = by_page[page]
                data = zf.read(arcname)
                assert data.startswith(FERNET_TOKEN_PREFIX), (
                    f'Collection page "{arcname}" is not an encrypted image payload.'
                )
