"""Kivy-free navigation domain model.

Provides `Destination` descriptors and a `NavigationModel` that answers navigation
policy questions ("what view state for this destination?", "does it auto-select a
descendant?") independently of the Kivy tree-view widget.
"""

from .destinations import (
    AllSeriesDestination,
    AppendixDestination,
    ArticleDestination,
    CategoriesDestination,
    CategoryDestination,
    CensorshipFixesDocDestination,
    ChooseForMeDestination,
    ChronologicalDestination,
    Destination,
    HistoryDestination,
    IndexDestination,
    IntroDestination,
    IntroDocDestination,
    LocationsIndexDestination,
    MainIndexDestination,
    NamesIndexDestination,
    RandomTitlesDestination,
    ReadingDestination,
    SearchDestination,
    SeriesDestination,
    SpeechIndexDestination,
    SpeechWordsDestination,
    StatisticsDestination,
    StoriesDestination,
    TagDestination,
    TagGroupDestination,
    TagSearchDestination,
    TitleDestination,
    TitleSearchDestination,
    WikiIndexDestination,
    WordSearchDestination,
    YearRangeDestination,
    YearRangeKind,
)
from .navigation_model import NavigationModel
from .tree_spec import (
    NodeKind,
    NodeRegistration,
    NodeSpec,
    PressAction,
    build_reader_tree_spec,
)

__all__ = [
    "AllSeriesDestination",
    "AppendixDestination",
    "ArticleDestination",
    "CategoriesDestination",
    "CategoryDestination",
    "CensorshipFixesDocDestination",
    "ChooseForMeDestination",
    "ChronologicalDestination",
    "Destination",
    "HistoryDestination",
    "IndexDestination",
    "IntroDestination",
    "IntroDocDestination",
    "LocationsIndexDestination",
    "MainIndexDestination",
    "NamesIndexDestination",
    "NavigationModel",
    "NodeKind",
    "NodeRegistration",
    "NodeSpec",
    "PressAction",
    "RandomTitlesDestination",
    "ReadingDestination",
    "SearchDestination",
    "SeriesDestination",
    "SpeechIndexDestination",
    "SpeechWordsDestination",
    "StatisticsDestination",
    "StoriesDestination",
    "TagDestination",
    "TagGroupDestination",
    "TagSearchDestination",
    "TitleDestination",
    "TitleSearchDestination",
    "WikiIndexDestination",
    "WordSearchDestination",
    "YearRangeDestination",
    "YearRangeKind",
    "build_reader_tree_spec",
]
